### ISSUE TITLE
Where is the Output directory?

### ISSUE THREAD

**Issue by CrawfordGriffith** [wwarthen/RomWBW#1]
Hi,

There appears to be no Output directory and no Rom images.  Either the directory is renamed, or missing.  

Regards, Crawford

**Comment by wwarthen** [comment]
Hi Crawford,

The Output directory is created and populated by the build process.  The pre-built ROM images are included in the "release" distributions.  When looking at the project in GitHub, click on the "releases" tab, find the release you want, and download the zipfile named RomWBW-X.X-Package.zip and you will find the Output directory with all of the prebuilt ROM images.
