### ISSUE TITLE
unable to start COM version of hbios

### ISSUE THREAD

**Issue by vipoo** [wwarthen/RomWBW#142]
Hi,

I am not 100% sure if its me or not - but with the latest version, I am not able to start the COM version of HBIOS -- produces no output

When i roll back to before commit 8ef44563230501f70c122aa7bdf46cefbdce707a, everthing works ok.

This weekend i had transitioned to a differnt board (first board i designed) - and am not sure if its something i have screwed up.

I see in the commit, there was code to manage interrupts during bankcpy/peek and poke, (now commented out) - i guess the code would only renable interrupts if not previously disabled.

Dean

**Comment by wwarthen** [comment]
Yeah, pretty sure this is part of what I fixed with the check-in I jsut did.  Can you try again with the latest?

I got excited that I had Z280 working and failed to do adequate regression testing.  Pretty sure it is all good again.

-Wayne

**Comment by vipoo** [comment]
All working now .

Cheers
Dean

**Comment by wwarthen** [comment]
Thanks Dean.
