### ISSUE TITLE
BuildImages.cmd: "hdnew" single slice images are missing the prepended "hdnew_prefix.bin" file

### ISSUE THREAD

**Issue by trawlergeek** [wwarthen/RomWBW#146]
In the "dev" branch (RomWBW 3.1.1.pre21), the combo hdnew image works just fine. It has the "hdnew_prefix.bin" up front.
I tested the hypothesis by prepending the cpm3 image with the "hdnew_prefix.bin file and the modified image booted correctly.

**Comment by trawlergeek** [comment]
Potential addition (at the end)  to the Build.cmd file for images:

echo.
echo Building Final Disk (1024 DIR) cpm22 Image...
copy /b hdnew_prefix.bin + ..\..\Binary\hdnew_cpm3.img ..\..\Binary\hdnew_cpm3_1024.img

echo Building Final Disk (1024 DIR) zsdos Image...
copy /b hdnew_prefix.bin + ..\..\Binary\hdnew_zsdos.img ..\..\Binary\hdnew_zsdos_1024.img

echo Building Final Disk (1024 DIR) nzcom Image...
copy /b hdnew_prefix.bin + ..\..\Binary\hdnew_nzcom.img ..\..\Binary\hdnew_nzcom_1024.img

echo Building Final Disk (1024 DIR) cpm3 Image...
copy /b hdnew_prefix.bin + ..\..\Binary\hdnew_cpm3.img ..\..\Binary\hdnew_cpm3_1024.img

echo Building Final Disk (1024 DIR) zpm3 Image...
copy /b hdnew_prefix.bin + ..\..\Binary\hdnew_zpm3.img ..\..\Binary\hdnew_zpm3_1024.img

echo Building Final Disk (1024 DIR) ws4 Image...
copy /b hdnew_prefix.bin + ..\..\Binary\hdnew_ws4.img ..\..\Binary\hdnew_ws4_1024.img

**Comment by trawlergeek** [comment]
Is there a resolution to be applied or should we go ahead and close this issue?
Thanks!
Jim

**Comment by wwarthen** [comment]
> Is there a resolution to be applied or should we go ahead and close this issue?

I have an idea that I am going to explore shortly.  I hope it will make things cleaner, but not sure yet.  Let's leave this open until I try it and get some feedback from you and possibly others.

-Wayne

**Comment by wwarthen** [comment]
So, I tried a few ideas including the suggestion of post-processing to create individual images with the prefix.  However, it seemed more confusing than helpful to have the extra images when I tried to ducment everything.  I have renamed some files to try and make everything more obvious and I have tried to document the situaiton in the ReadMe.txt file in the Images directory.

I'm about out of ideas, but open to further suggestions.

Thanks, Wayne

**Comment by trawlergeek** [comment]
Wayne,
Your effort to document the requirement to prefix the hd1024 images is perfect. It is very clear what is intended there.
I agree with your decision not to auto-generate all the image variants. And it is not difficult for the user to modify the script to produce precisely what meets their needs.

Thanks so very much for your efforts.
Jim

**Comment by trawlergeek** [comment]
Let's close this...

**Comment by wwarthen** [comment]
Thanks for your input and assistance with this Jim.

-Wayne
