### ISSUE TITLE
INITDIR in ROM Space is unstable and fails when used with the new 1024 DIR HD images.

### ISSUE THREAD

**Issue by trawlergeek** [wwarthen/RomWBW#147]
For CPM3 images, INITDIR crashes or locks up the system when trying to run it against the "new" versions of the HD images.
I assume that INITDIR has a dependence on the DIR entries size.

**Comment by trawlergeek** [comment]
This issue has been investigated a bit further. It appears that the INITDIR.COM in the ROM space is only 2KB in size while the INITDIR in the disk image builds is 32KB in size. Experimental substitution of the 32KB version for the 2KB version in the ROM space results in a viable INITDIR in the ROM space. MD0: INITDIR.COM works after the  replacement.
Also, not sure INITDIR.CFG is relevant with the 32KB version.

**Comment by wwarthen** [comment]
Hi Jim,

Finally getting back to investigating this issue.

As you discovered, there are two INITDIR applications.  One is associated with ZSDOS and initializes a directory for P2DOS date stamping.  The other is associated with CP/M 3 and initializes a directory for CP/M 3 date stamping.  In theory P2DOS date stamps have the same directory format as CP/M 3; however, the two applications must be run in the context of their associated OS.

As long as I used the correct application for the running OS, I was able to initialize a 1024 entry directory and the save and display file dates successfully.

I suspect that I am not recreating the problem scenario you are seeing.  Can you provide me with explicit instructions on how to create the error you are seeing?  Ideally, if you can capture a session log that demonstrates the error, that would be best.

By the way, all of my testing is in the dev branch.  Let me know if you are using the master branch and I will test there if so.

Thanks,

Wayne

**Comment by trawlergeek** [comment]
Hi Wayne.
I just re-read the posts here. It has been some time. Glad to see you are getting settled in the new location. I was using the "dev" branch when I encountered the episode.

Originally, I was perplexed by the contents of the MD0: ROM Drive that contained the INITDIR.COM version that is normally associated with the ZSDOS OS.  I originally suspected it was as a result of building the combo image which leads to another question:     How does the build script decide what files to place into the MD0: ROM drive?

I have to admit that I have not done my homework - I should take time to look in detail to find the answer to my inquiry - a good learning path!  
Sorry about that.

When I build a CPM3 hard disk image, the MD0: ROM drive does contain the expected CPM3 compatible tools and applications.
Recently, I settled on use of homogeneous hard disk images (one OS) when I build physical drives. And I use the MD0: drive contents as proper "standards" for the specific RomWBW version - I propagate those "standards" to any other drive that is expected to work with the ROM version of RomWBW. Consistency is maintained in a manner you disclose in the guidance.

I will next try to understand how the MD0: ROM disk files as selected for a specific build of RomWBW....   A good assignment!
I will try to examine the combo build and see if I can recreate the original circumstances.

Cheers
Jim

**Comment by trawlergeek** [comment]
Oh, one more thing. I am also unable to account for the differences in the file sizes from the earlier post:
"It appears that the INITDIR.COM in the ROM space is only 2KB in size while the INITDIR in the disk image builds is 32KB in size."
This is more suspicious but can be confirmed when looking at the source of the d_zsdos files...
It appears that the ROm drive was populated with the INIT.DIR from \dev\Source\Images\d_zsdos\u0.

I think I should have realized that a combo image can only satisfy one "set association" for populating the MD0: ROM disk with contents that support a single OS instance - not 5 (less WS4).

Cheers
Jim

**Comment by wwarthen** [comment]
Hi Jim,

> Originally, I was perplexed by the contents of the MD0: ROM Drive that contained the INITDIR.COM version that is normally associated with the ZSDOS OS. I originally suspected it was as a result of building the combo image which leads to another question: How does the build script decide what files to place into the MD0: ROM drive?

The content of the ROM drive (MD0:) is completely static in all builds.  The files come from \Source\RomDsk\ROM_512KB. The ROM drive is intended to support the use of the bootable ROM OSes (specifically CP/M 2.2 and ZSDOS).  So, the files on the ROM drive are the standard CP/M 2.2 distribution files combined with selected ZSDOS distribution files (and a few utility programs like ZDE).  Since ZSDOS is almost entirely CP/M 2.2 compatible, this provides a nice set of files for use with the ROM OS boot options.  The files in the ROM drive are close to useless when you boot from a hard disk slice.  As you have seen, the booted slice becomes A: so that the files appropriate to the booted OS are generally on A: (or B: in the case of a ROM OS boot because A: needs to be writable).

> I have to admit that I have not done my homework - I should take time to look in detail to find the answer to my inquiry - a good learning path!
> Sorry about that.

No problem at all.  If there is any confusion, I'm sure others are also confused.  This type of discussion will help many.  It will also provide some fuel for improving the official documentation.

> When I build a CPM3 hard disk image, the MD0: ROM drive does contain the expected CPM3 compatible tools and applications.

Hmmm... Are you modifying the ROM drive contents for your build?  Unless you do, the ROM drive should not contain any CP/M 3 applications.

> Recently, I settled on use of homogeneous hard disk images (one OS) when I build physical drives. And I use the MD0: drive contents as proper "standards" for the specific RomWBW version - I propagate those "standards" to any other drive that is expected to work with the ROM version of RomWBW. Consistency is maintained in a manner you disclose in the guidance.

Ah, so it sounds like perhaps you are customizing the contents of the ROM drive for your build.  That is fine and makes sense for your goals.

> I will next try to understand how the MD0: ROM disk files as selected for a specific build of RomWBW.... A good assignment!
> I will try to examine the combo build and see if I can recreate the original circumstances.

Sounds good.  I will stand by.

Thanks!

**Comment by wwarthen** [comment]
> Oh, one more thing. I am also unable to account for the differences in the file sizes from the earlier post:
> "It appears that the INITDIR.COM in the ROM space is only 2KB in size while the INITDIR in the disk image builds is 32KB in size."

Yeah, this is expected.  The 2K INITDIR is from ZSDOS and the 32K INITDIR is from CP/M 3.

**Comment by trawlergeek** [comment]
Here is a bit more that starts to explain my experiences:

Looking in these locations for INITDIR.COM : 
https://github.com/wwarthen/RomWBW/tree/**master**/Source/RomDsk/ROM_512KB
https://github.com/wwarthen/RomWBW/blob/**dev**/Source/RomDsk/ROM_512KB
When I click them individually I see a raw file size of 2KB for each instance. The ZSDOS version.

Both are the zsdos version with a length of 2KB with an accompanying .CFG file. I think the issue I "recently encountered" was due to changing a historical use of a "floppy disk" image version of CPM3 to distribute the "standard files" to the use of the MD0: versions. The floppy was convenient as a test bed for the floppy drives as well as to clean up other hard drives when updating RomWBW for the multiple systems I have deployed - each with a floppy and an ROM Image.

When I experienced the original issue, it is clear that I used the (dev or master)  version of INITDIR.COM from the MD0: ROM Drive which produced the issues - from \Source\RomDsk\ROM_512KB.

Yes, to replace the ZSDOS INITDIR.COM, I modified the standard files for the ROM disk_512 case. I copied the 24KB version into the ROM_512KB space. The space may be corrupt due to overflowing the available disk space. I failed to check that. In any event, though, the CP/M 3 INITDIR.COM is now included in my build of the ROM Disk. I will check the disk space usage and adapt...

Thanks!

Jim

**Comment by trawlergeek** [comment]
Perhaps we can close this issue?
It appears that the contents of the ROM drive are precisely as intended and that the user should be responsible for modifying it to suit the actual circumstances.

**Comment by trawlergeek** [comment]
One more comment after rereading your replies:
**"Unless you do, the ROM drive should not contain any CP/M 3 applications."**

I have resolved to selectively replace ALL the files in the ROM_512KB with the CPM3 set from \dev\Source\Images\d_cpm3\ and additional files \dev\Source\Images\Common

THANKS!!
Jim

**Comment by trawlergeek** [comment]
Issue due to user interactions and not a fundamental defect.

Thanks!

**Comment by wwarthen** [comment]
Thanks for your help working through this Jim!
