### ISSUE TITLE
HBIOS/sd.asm uses OUT to access Z180 register, should be OUT0

### ISSUE THREAD

**Issue by durgadas311** [wwarthen/RomWBW#170]
When doing the final initialization of the CSIO, sd.asm does:
```
	CALL	SD_WAITTX		; MAKE SURE WE ARE DONE SENDING
	XOR	A			; ZERO MEANS MAX SPEED
	OUT	(Z180_CNTR),A		; NOW SET CSIO PORT
```
I'm not sure all the possible problems with using OUT here, but according to Z180 documentation, OUT0 should be used to access Z180 registers. It appears to work, in some cases, but it is not clear that one can depend on this always working.

This code is also inconsistent about using SD_CNTR vs. Z180_CNTR.

**Comment by wwarthen** [comment]
Yikes.  Thank you for catching this Douglas.  CSIO was probably not transitioning to high speed in many cases.

I will fix soon, but may not be today due to holiday obligations.

Thanks!

Wayne

**Comment by wwarthen** [comment]
Corrected in dev branch.
