### ISSUE TITLE
Question:  SYSGETBNK($F3)  and SYSSETBNK($F2) RST 08 BIOS calls

### ISSUE THREAD

**Issue by jrlodden** [wwarthen/RomWBW#174]
When using these calls is it safe to use $SYSGETBNK and assume the BIOS bank is the next bank down?  
(Using the SC126 Z180 board with 512k RAM & ROM )

If so, is the next bank below that free to use using $SYSSETBNK.
My use case is I have TurboDOS booting non-banked switched with access to all devices via the RST 08 bios calls.
I would like to set up a TurboDOS bank switch driver which calls $SYSGETBNK / $SYSSETBNK to access another 32K for a larger TPA. 

Is this the correct direction or do I need to look at other BIOS calls?

Thanks for your assistance.

-jrl

**Comment by wwarthen** [comment]
Hi John,

I am out of town right now and not enough time to answer properly right
now.  I think I have time later today and will get back to you as soon as I
can.

Wayne

**Comment by wwarthen** [comment]
Hi John,

Very sorry for the slow response.  I'm not home, but will try to provide some guidance.

First, be aware that there is no API within RomWBW that is used to reserve or assign RAM banks.  I intend to do something about this someday, but at present, the use of the RAM banks is done by convention.

It may seem odd, but the RAM banks are currently assigned starting from the highest RAM bank.  So, I will refer to RAM bank assignments as n, n-1, n-2, etc., where n refers to the highest numbered RAM bank.

At this time, the RAM bank assignments are as follows:

Bank n: Common Bank mapped to high CPU address space (8000H - FFFFH)
Bank n-1: User Bank (basically, the lower CPU address space for applications (0000H - 7FFFH)
Bank n-2: HBIOS Bank
Bank n-3: Aux Bank 0: BPBIOS or CP/M 3
Bank n-4: Aux Bank 1 CP/M 3
Bank n-5: Aux Bank 2 CP/M 3
Bank n-6: Aux Bank 3 CP/M 3
Bank n-7: Aux Bank 4 CP/M 3
Bank n-8 to Bank 0: RAM Disk

Assuming you are not using CP/M 3 or BPBIOS, it would be fine to use any/all of the AUX banks.  The best way to determine the "top" aux bank is to use the API function 0xF8, subfunction 0xF2 (BNKINFO).  It will return the BIOS bank id in register D.  You can assume that the top AUX banik is one berlow this.

Let me know if you have any further questions.

Thanks,

Wayne

**Comment by jrlodden** [comment]
Thank you very much -- I really appreciate the insight!

I now have TurboDOS 1.43 bank switch driver now working!
It is great having a 62k TPA again.  With the removal of debugging double buffering, I should get another 1k back in the TPA.

TurboDOS can now self-host all of its development and system generations now.
I am now off to clean up the disk drivers and get the network driver running to connect to my other TurboDOS 86 16-bit and  8-bit machines.

Thanks again! 

-jrl

**Comment by wwarthen** [comment]
Sounds like this is resolved.  Closing the issue.
