### ISSUE TITLE
Question: osimg  file size

### ISSUE THREAD

**Issue by yonglak** [wwarthen/RomWBW#177]
Hi,
The file size of osimg and osimg are 34K and 33k resp in romWBW 3.01. Should it be in 32k chunks?.

**Comment by b1ackmai1er** [comment]
Hello is this with the linux build or windows build. Should be 32k.

regards phil

**Comment by yonglak** [comment]
Hi,
Windows 7  build. Poweshell. I just added the file sizes of the various components used to make osimg and osimg.

**Comment by yonglak** [comment]
Hi, sorry. Osimg and Osimg are 32K. I'm not sure why the individual components add to 34k and 33k. It does work with 512k eprom and 256k flash eprom (reduced img size).

**Comment by yonglak** [comment]
Hi, maybe its just 1K=1024 bytes stuff. I was trying to use 256K flash eeprom and make a little more Romdisk space by removing some rom/os apps. This is for my Zworld PK2200 Z180 board. 
Anyway it works well on my SCZ180 board as it is. 
Thanks for RomWBW

Concat '..\Forth\camel80.bin', 'nascom.bin', 'tastybasic.bin', 'game.bin', 'imgpad0.bin', 'usrrom.bin' osimg1.bin

   File sizes respectively (6K + 8K + 3K + 3K + 10K + 4K ) = 34K.

**Comment by b1ackmai1er** [comment]
Hi

Yes all of those add up to 32Kb

5888
8192
2304
2304
9984
4096

RomWBW is Waynes work and is pretty awesome indeed. Good luck getting it to
work on another platform.

**Comment by wwarthen** [comment]
Sounds like this is resolved, so I am going to close it.

Thanks for answering Phil!
