### ISSUE TITLE
ACIA - RTS flow control bit not asserted

### ISSUE THREAD

**Issue by feilipu** [wwarthen/RomWBW#189]
I'm digging in the ACIA code, and I think there is an issue with asserting RTS.

The [code here](https://github.com/wwarthen/RomWBW/blob/master/Source/HBIOS/acia.asm#L292), tries this.
``` asm
	LD	A,(ACIA_CMD)		; CONFIG BYTE W/O RTS BIT
	OR	ACIA_RTSON		; SET RTS
	OUT	(C),A			; DO IT
```
but `ACIA_RTSON` looks like this.
```asm
ACIA_RTSON	.EQU	%00000000	; BIT MASK TO ASSERT RTS
```
so the code does nothing.

It should do something like
``` asm
ACIA_RTSON	.EQU	%10111111	; BIT MASK TO ASSERT RTS
;
	LD	A,(ACIA_CMD)		; CONFIG BYTE W/O RTS BIT
	AND	ACIA_RTSON		; SET RTS
	OUT	(C),A			; DO IT
```

Thoughts?

There's a few other (unrelated) cleanups I'd also like to make.

For instance, the detection routine relies on the implementation (specifically the RC2014 ACIA Module with loose addressing) rather than characteristics of the ACIA device itself. I would like to change this to use the specific addresses nominated (0x80 and 0x40) and seek characteristics from the device. Perhaps adding build time config checks to avoid SIO clashes would be good too?

Should I do a PR?

**Comment by wwarthen** [comment]
By all means, send a PR with anything you can improve.  Just make sure it is against the dev branch.

Regarding setting RTS.  Yes, I agree, the code is a bit strange.  It does actually work in the current form because the config byte is guaranteed to have the RTS bit clear prior to the OR.  Essentially, the OR is not even needed.

On the detect routine.  Are you looking at the dev branch or the master branch?  I think the dev branch already has this corrected.

Thanks!

Wayne

**Comment by feilipu** [comment]
Yes. Noted, that the detection routine is changed / fixed in `dev`. I'll build against that instead.

I've done a whitespace fix (remove tabs for 8 spaces and align), and will fix the RTS first (though you've noted it is not required).

But, leave the PR as draft until I'm happy.

Cheers, Phillip

**Comment by wwarthen** [comment]
I have merged #191.  I assume this addresses this issues and will close it now.  Happy to reopen it if anything further needs to be resolved.

Thanks,

Wayne

**Comment by feilipu** [comment]
Wayne, just noted that I took tidying the wrong way by converting tabs to spaces. RomWBW uses tabs, and the acia.asm file was mixed. Would you want me to PR a reversion to clean tabs?

**Comment by wwarthen** [comment]
> Wayne, just noted that I took tidying the wrong way by converting tabs to spaces. RomWBW uses tabs, and the acia.asm file was mixed. Would you want me to PR a reversion to clean tabs?

Actually, it has been my intent to switch from tabs to spaces for all the RomWBW files at some point.  I think that is the better format considering the vagaries of how different editors handle tabs.  So, just leave asia.asm as is and the rest of RomWBW will eventually catch up to it.

Thanks,

Wayne
