### ISSUE TITLE
Question - ACIA & bugfixes in pre.50 & pre.55

### ISSUE THREAD

**Issue by feilipu** [wwarthen/RomWBW#196]
I'm having some issues with the RC2014 SIO + ACIA build in the most recent dev pre.58

This is all with `BOOTCON` set  to 2, and one SIO configured and found.

One of my concerns is [disabling interrupts in the `dbgmon` parser.](https://github.com/wwarthen/RomWBW/commit/a1a25465dacc1c48c734f34bf2522401d8385d52#diff-4c81f6c8f84802bd14ef0288778b9e7ca39a60e4c20d2585cfcc8b829f005572L47), which affects the UX Module ACIA Emulation. But, that's something I could/can fix. But, is there a bug fix necessary for what has been working for the past few years?

But my real concern is that the emulated ACIA doesn't show up in enumeration any more at `0x40`.

And separately although a real ACIA is attached at `0x80` and seems to work properly at `0x40` (because build config unchanged from `0x40`) it doesn't show up in enumeration either. See below `dbgmon` output on the ACIA serial port.

(A side issue that something that hasn't been enumerated shouldn't really be expected to exist, and therefore to work).

```
RomWBW HBIOS v3.1.1-pre.58, 2021-03-10

RC2014 Z80 @ 7.372MHz
0 MEM W/S, 1 I/O W/S, INT MODE 1, Z2 MMU
512KB ROM, 512KB RAM

SIO0: IO=0x80 SIO MODE=115200,8,N,1
SIO1: IO=0x82 SIO MODE=115200,8,N,1
MD: UNITS=2 ROMDISK=384KB RAMDISK=256KB
PPIDE: IO=0x20 PPI NOT PRESENT

Unit        Device      Type              Capacity/Mode
----------  ----------  ----------------  --------------------
Char 0      SIO0:       RS-232            115200,8,N,1
Char 1      SIO1:       RS-232            115200,8,N,1
Disk 0      MD1:        RAM Disk          256KB,LBA
Disk 1      MD0:        ROM Disk          384KB,LBA

RC2014 Boot Loader

Boot [H=Help]:
```

Is there some other changed behaviour along with the `BOOTCON` setting, that you've noticed?

**Comment by wwarthen** [comment]
> One of my concerns is [disabling interrupts in the `dbgmon` parser.](https://github.com/wwarthen/RomWBW/commit/a1a25465dacc1c48c734f34bf2522401d8385d52#diff-4c81f6c8f84802bd14ef0288778b9e7ca39a60e4c20d2585cfcc8b829f005572L47), which affects the UX Module ACIA Emulation. But, that's something I could/can fix. But, is there a bug fix necessary for what has been working for the past few years?

I thought that interrupts were enabled when dbgmon is entered, so the EI should have been superfluous.  There is certainly no problem restoring the EI there in the meantime.

> But my real concern is that the emulated ACIA doesn't show up in enumeration any more at `0x40`.

This seems odd.  I don't see any recent changes to the ACIA probe logic.  Are you saying that the emulated ACIA **does** get enumerated when it is set for 0x80, but does **not** get enumerated when it is set for 0x40?

By the way, neither a real nor emulated ACIA should be detected/enumerated at 0x40 without a small config change.  I think that is the way the behavior has been for a long time.

> And separately although a real ACIA is attached at `0x80` and seems to work properly at `0x40` (because build config unchanged from `0x40`) it doesn't show up in enumeration either. See below `dbgmon` output on the ACIA serial port.

I don't quite understand.  A real ACIA is at 0x80, but it is working at 0x40?  Not sure what you mean by "working" in this context.  If it is not enumerated, then it should not be possible to refer to it at all in RomWBW.  Can you clarify?

> Is there some other changed behaviour along with the `BOOTCON` setting, that you've noticed?

I have not noticed anything, but I could certainly have introduced a bug inadvertently.

I reviewed the ACIA changes in pre.50 and pre.55.  I don't see anything that would impact device discovery.

Sorry if I am being dense here -- just try to get me pointed in the right direction.

Thanks,

Wayne

**Comment by feilipu** [comment]
Thanks for clarification there's no intent to change previous behaviours.

Let me look at the case further. If there is anything to address I'll PR it. Cheers.

**Comment by feilipu** [comment]
Hmm. Too many moving parts. Sorry nothing to see here. :+1: 

My correctly configuredCIA Emulation at `0x40` is detected and operates correctly.

```
RomWBW HBIOS v3.1.1-pre.58, 2021-03-10

RC2014 Z80 @ 7.372MHz
0 MEM W/S, 1 I/O W/S, INT MODE 1, Z2 MMU
512KB ROM, 512KB RAM

SIO0: IO=0x80 SIO MODE=115200,8,N,1
SIO1: IO=0x82 SIO MODE=115200,8,N,1
ACIA0: IO=0x40 ACIA MODE=115200,8,N,1
MD: UNITS=2 ROMDISK=384KB RAMDISK=256KB
PPIDE: IO=0x20 PPI NOT PRESENT

Unit        Device      Type              Capacity/Mode
----------  ----------  ----------------  --------------------
Char 0      SIO0:       RS-232            115200,8,N,1
Char 1      SIO1:       RS-232            115200,8,N,1
Char 2      ACIA0:      RS-232            115200,8,N,1
Disk 0      MD1:        RAM Disk          256KB,LBA
Disk 1      MD0:        ROM Disk          384KB,LBA

```
What caused me a lot of confusion though is how my standard ACIA Module (nominally configured for `0x80`), and also (correctly) not detected by RomWBW, can actually act as the boot monitor?

The below text is output on my ACIA Module, and serial inputs are also recognised.

```
RomWBW HBIOS v3.1.1-pre.58, 2021-03-10

RC2014 Z80 @ 7.372MHz
0 MEM W/S, 1 I/O W/S, INT MODE 1, Z2 MMU
512KB ROM, 512KB RAM

SIO0: IO=0x80 SIO MODE=115200,8,N,1
SIO1: IO=0x82 SIO MODE=115200,8,N,1
MD: UNITS=2 ROMDISK=384KB RAMDISK=256KB
PPIDE: IO=0x20 PPI NOT PRESENT

Unit        Device      Type              Capacity/Mode
----------  ----------  ----------------  --------------------
Char 0      SIO0:       RS-232            115200,8,N,1
Char 1      SIO1:       RS-232            115200,8,N,1
Disk 0      MD1:        RAM Disk          256KB,LBA
Disk 1      MD0:        ROM Disk          384KB,LBA

RC2014 Boot Loader
Boot [H=Help]: m
Loading Monitor...
Monitor Ready (H for Help)
>
```
So something working when it shouldn't? Odd.

**Comment by wwarthen** [comment]
> Hmm. Too many moving parts. Sorry nothing to see here. 🤷‍♂️

Glad there is nothing seriously wrong.

> What caused me a lot of confusion though is how my standard ACIA Module (nominally configured for `0x80`), using the identical ROM and (correctly) not detected by RomWBW, can actually act as the boot monitor?

This is **very** confusing to me as well.  Is there any possibility the output was actually coming from SIO0?  I ask because if BOOTCON is set to a character unit number greater than anything in the system, the code reverts the console back to character unit 0 (I thought that was a an appropriate failsafe).

I would like your thoughts on a related idea.  I am still less than thrilled with the way that BOOTCON works.  The problem is that you need to know which unit number will be assigned to each interface when you build your ROM.  The unit numbers are dynamic depending on the hardware actually installed in the system, so this is problematic.  I am thinking it would be better to have each interface in the config file be able to declare whether it wants to be the boot console.  Done this way, it would not matter which unit number it was assigned, it would still become the boot console as long as that particular interface was in the system.  Is this worth doing or is it more complication than warranted?

**Comment by feilipu** [comment]
It just struck me why. Both (all) the serial modules share the Tx/Rx lines on the RC2014 backplane. So I bet the SIO is driving those lines, and the FTDI adapter attached to the ACIA is reading / writing into that.

So I think we can put this to bed. But interesting nevertheless.

**Comment by wwarthen** [comment]
> It just struck me why. Both (all) the serial modules share the Tx/Rx lines on the RC2014 backplane. So I bet the SIO is driving those lines, and the FTDI adapter attached to the ACIA is reading / writing into that.
> 
> So I think we can put this to bed. But interesting nevertheless.

OK, agreed.  Closing the issue.

**Comment by feilipu** [comment]
Regarding the BOOTCON configuration, it is a bit fragile, and your suggestion is the right way to fix it. But I don't know whether it is just "make work" to try to do better, or indeed a good use of your time.

From my point of view, I'm happy with current result.

Perhaps just document your thoughts into the code comments, and come back if there more complex use cases coming up?

**Comment by wwarthen** [comment]
> Perhaps just document your thoughts into the code comments, and come back if there more complex use are cases coming up?

I like it.  Thanks for your input.
