### ISSUE TITLE
PPIDE drive init fails with non-compactflash drives

### ISSUE THREAD

**Issue by electrified** [wwarthen/RomWBW#2]
Hi Wayne.

First of all many thanks for RomWBW, it's great.

Now onto the problem. I'm happy to contribute a code fix, but wondered what the best way to proceed was.

The ppide driver doesn't seem to work with non-compactflash devices. This is due to if PPIDE8BIT is set to false, in PPIDE_INITDEV the set feature command is called with PPIDE_FEAT_DISABLE8BIT. The enable/disable 8 bit PIO transfer mode features are only supported on devices that support the CFA feature set and causes an error on the rotating disc IDE drives I've tried it on, resulting in the init bailing out.

Code is here: https://github.com/wwarthen/RomWBW/blob/master/Source/HBIOS/ppide.asm#L1005

I got the drive working by commenting out this part of the code.

The code could:

- Detect if the CFE feature set is supported and only attempt to set feature if it is
- Don't disable 8 bit mode if PPIDE8BIT is false. Drives start off in 16-bit mode, so I don't see the downside of this?
- Not end the detection process if setting the feature flag fails

What do you think the best fix is?

Hardware is an RC2014 with my own 82c55 IDE adapter (https://github.com/electrified/rc2014-82c55-ide)

I've been looking at page 180 of the ATA spec for what features are supported etc: http://www.t13.org/documents/uploadeddocuments/docs2006/d1699r3f-ata8-acs.pdf

Best regards,
Ed

**Comment by wwarthen** [comment]
Thanks for tracking this down!

Unfortunately, some CF devices do not accurately identify themselves as a CF device.  I will probably ignore failure if attempt to disable 8 bit mode fails.  I will incorporate this fix in the next release which will be in the next few days.

-Wayne

**Comment by wwarthen** [comment]
This issue should be corrected in v0.8.6-pre.0 which was just posted.

Thanks again for tracking this down @electrified -- made it very easy to fix!

Wayne

**Comment by electrified** [comment]
Hi Wayne,

Many thanks for the fast response.

I've had a look at the code change and see it's in ide.asm

For my use with 82c55 "parallel port" driven IDE the fix also needs to be applied to the same logic in Source/HBIOS/ppide.asm. 

Best regards,
Ed

**Comment by wwarthen** [comment]
Hi Ed,

Well, that's embarrassing.  Thanks for once again catching my problem.  I am going to reopen this issue and close it after once I check in the corresponding fix in ppide.asm.

Thanks!

Wayne

**Comment by electrified** [comment]
Closed now https://github.com/wwarthen/RomWBW/pull/3 is merged.
