### ISSUE TITLE
Possible disk i/o problem.

### ISSUE THREAD

**Issue by jayacotton** [wwarthen/RomWBW#22]
Using the document "RomWBW Architecture" to write a disk sector dumper program.

I don't seem to be reading the sector.  I see activity (PPIDE) light but all I get is zeros.

attached is a copy of the code.  Perhaps there is a simple/obvious reason this does not work.
none of the functions return an error code, so they think they are working.  

This code is z88dk sbcc targeted for rc2014 cpm.

/* read and dump in hex/ascii each sector on a track */

#include <stdio.h>

char Buffer[1024]; 
unsigned int RBC;
unsigned int RDE;
unsigned int RHL;
unsigned char RB;
unsigned char RC;
unsigned char RD;
unsigned char RE;
unsigned char RH;
unsigned char RL;

unsigned char ATTR;
unsigned char TYPE;
unsigned char DEVNUM;

#define WbwSEEK 0x12
#define WbwREAD 0x13
#define WbwDEVID 0x17

#define CHS 0
#define LBA 1

int error;

int
WbwDevId (int unit)
{
  error = 0;
  RB = WbwDEVID;
  RC = unit;
  printf ("Drive unit %d ", unit);
#asm
  ld a, (_RB)
    ld b, a
    ld a, (_RC)
    ld c, a
    rst 8
    ld (_error), a
    ld a, c 
    ld (_ATTR), a 
    ld a, d 
    ld (_TYPE), a 
    ld a, e 
    ld (_DEVNUM), a
#endasm
  if (ATTR & 0x80)
    {				/* floppy */
      printf (" floppy");
    }
  else
    {				/* hard drive */
      printf (" hard drive dev nr %d", DEVNUM);
      switch ((TYPE & 0xf0) >> 4)
	{
	case 0:
	  printf (" memory disk");
	  break;
	case 1:
	  printf (" floppy disk");
	  break;
	case 2:
	  printf (" ram floppy");
	  break;
	case 3:
	  printf (" IDE disk");
	  break;
	case 4:
	  printf (" ATAPI disk");
	  break;
	case 5:
	  printf (" PPIDE disk");
	  break;
	case 6:
	  printf (" SD Card");
	  break;
	case 7:
	  printf (" PropIO SD Card");
	  break;
	case 8:
	  printf (" ParPortProp SD Card");
	  break;
	case 9:
	  printf (" SIMH HDSK disk");
	  break;		/* highly unlikely */
	default:
	  printf (" unk ");
	  break;
	}
      if (ATTR & 0x40)
	{
	  printf (" removable");
	}
      switch ((ATTR & 0x38) >> 3)
	{
	case 0:
	  printf (" hard");
	  break;
	case 1:
	  printf (" cf");
	  break;
	case 2:
	  printf (" sd");
	  break;
	case 3:
	  printf (" usb");
	  break;
	case 4:
	  printf (" rom");
	  break;
	case 5:
	  printf (" ram");
	  break;
	case 6:
	  printf (" ramf");
	  break;
	default:
	  printf (" unknown");
	  break;
	}
    }
  printf ("\n");
  return error;

}

/* return the boot device unit number */
int
WbwBootDev ()
{
  error = 0;
#asm
  ld bc, #0xf8e0
  rst 8 
  ld a, d 
  ld (_error), a
#endasm
    return error;
}

int
WbwSeekDisk (int subf, int unit, int head, int sector, int track)
{
  error = 0;

  RB = WbwSEEK;			/* function */
  RC = unit;			/* unit */
/* going for lba type seek */
  if (subf == LBA)
    {
      RDE = 0x8000;		/* sector */
      RHL = sector;		/* track */
    }
  else
    {
      RD = head;
      RE = sector;
      RHL = track;
    }
#asm
  ld a, (_RC)
    ld c, a
    ld a, (_RB) 
    ld b, a 
    ld de, (_RDE) 
    ld hl, (_RHL) 
    rst 8 
    ld (_error), a
#endasm
    printf("Seek to %d\n",sector);
    return error;
}

int
WbwReadDisk (int unit, int count, char *buff)
{
  error = 0;

  RB = WbwREAD;
  RC = unit;
  RE = count;
  RHL = (unsigned int) buff;
  printf ("read %d %d 0x%04x\n", RC, RE, RHL);
#asm
  ld a, (_RC)
    ld c, a
    ld a, (_RB) 
    ld b, a 
    ld a, (_RE) 
    ld e, a 
    ld hl, (_RHL) 
    rst 8 
    ld (_error), a
    ld a,e
    ld (_RE),a
#endasm
    printf("Blocks read %d\n",RE);
    return error;
}

int
WbwSyscall (int func, int subf, int unit, int count, char *buff,
	    int head, int sector, int track)
{
  if (func == WbwSEEK)
    {
      return (WbwSeekDisk (subf, unit, head, sector, track));
    }
  if (func == WbwREAD)
    {
      return (WbwReadDisk (unit, count, buff));
    }
  return -1;
}

Init ()
{
  memset (Buffer, 0, 512);
}

Dump ()
{
  /* use snap lib to dump the block */
  snapmem (0, Buffer, 512, 1, "Disk Sector");

}

void
main ()
{
  int i;
  int err;
  int drive;
int lba;
int nrecs;

  Init ();
  i = 0;
  for (i = 0; i <= 4; i++)
    {
      WbwDevId (i);
    }
  printf ("Boot drive is: %d\n", WbwBootDev ());
  printf ("Enter drive nr: ");
  scanf ("%d", &drive);
  printf("Start at LBA: ");
	scanf("%d", &lba);
  if (err = WbwSyscall (WbwSEEK, CHS, drive, 1, Buffer, 0, lba, 0))
    {
      printf ("Seek error:");
      exit (0);
    }
printf("How many sectors to dump: ");
scanf("%d",&nrecs);
  for (i = 0; i < nrecs; i++)
    {
      if (err = WbwSyscall (WbwREAD, LBA, drive, 1, Buffer, 0, lba+i, 0))
	{
	  printf ("Read error:");
	  exit (0);
	}
      Dump ();
    }
}

**Comment by jayacotton** [comment]
I found that the buffer address must be 0x8000 or higher.  With that I can read data.  Now, however the problem is that its reading the same sector every time.  I expected it to advance to the next sector
automatically ....

**Comment by jayacotton** [comment]
Well, it seems I can expect sequential sector reads to work.

**Comment by wwarthen** [comment]
@jayacotton, I see you closed the issue, so I assume everything is working OK at this point.  It sounds like I need to highlight the requirement to keep disk buffers in high memory.  Was there anything else about the behavior of RomWBW that you think should be improved?

Thanks,

Wayne

**Comment by jayacotton** [comment]
Hi Wayne:

Thanks for looking at this.  The only issue was the disk buffer address and
my lack of understanding.

I now have a working program for inspecting disk blocks on any of the
drives.

jc

**Comment by wwarthen** [comment]
OK, glad all is working.  I happen to be doing some work on the documentation now, so I will add a warning about the location of the disk buffer.
