### ISSUE TITLE
Errors when building for Zeta2

### ISSUE THREAD

**Issue by MockbaTheBorg** [wwarthen/RomWBW#28]
Hi there,

I (believe I) have followed the readme file correctly, but when I do the BuildRom step, it dies here:

tasm -t80 -g3 -dROMBOOT hbios.asm hbios_rom.bin hbios_rom.lst
TASM Z80 Assembler.       Version 3.2 September, 2001.
 Copyright (C) 2001 Squak Valley Software
tasm: pass 1 complete.
HBIOS PROXY STACK space: 34 bytes.
HBIOS INT space remaining: 158 bytes.
hbios.asm line 0896: Label not found: (PIO_4P)
hbios.asm line 0896: Label not found: (PIO_ZP)
hbios.asm line 1251: Label not found: (PIO_4P)
hbios.asm line 1251: Label not found: (PIO_ZP)
DSRTC occupies 471 bytes.
UART occupies 667 bytes.
PPP occupies 1400 bytes.
MD occupies 496 bytes.
FD occupies 2246 bytes.
hbios.asm line 2445: Label not found: (PIO_4P)
hbios.asm line 2445: Label not found: (PIO_ZP)
hbios.asm line 2445: Label not found: (PPI_SBC)
pio.asm line 0508: Label not found: (PIO_ZP)
pio.asm line 0512: Label not found: (PIO_4P)
pio.asm line 0520: Label not found: (PPI_SBC)
pio.asm line 0543: Label not found: (PIO_ZP)
pio.asm line 0586: Label not found: (PIO_4P)
PIO occupies 734 bytes.
HBIOS space remaining: 20806 bytes.
tasm: pass 2 complete.
tasm: Number of errors = 12
TASM returned exit code 1
At C:\tmp_nosync\Zeta2\RomWBW\Source\HBIOS\Build.ps1:122 char:29
+  . . . ($LASTEXITCODE -gt 0) {throw "TASM returned exit code $LASTEXITCODE"}
+                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (TASM returned exit code 1:String) [], RuntimeException
    + FullyQualifiedErrorId : TASM returned exit code 1

PS C:\tmp_nosync\Zeta2\RomWBW\Source>`

Not sure what to do to fix it.
I am building with the ZETA2_std configuration. All vanilla.

Thanks a lot!

**Comment by wwarthen** [comment]
This is a problem with a recent source change.  I will post a fix later
today.  Sorry.

Wayne

**Comment by b1ackmai1er** [comment]
Hi Please add

PIO_4P		.EQU	FALSE		; TRUE FOR ECB-4PIO PIO SUPPORT
PIO_ZP		.EQU	FALSE		; TRUE FOR ECB-ZILOG PERIPHERALS BOARD
PPI_SBC		.EQU	FALSE		; TRUE FOR SBC V1/V2 8255 PPI

to Source\HBIOS\cfg_zeta.asm

Sorry will do a build test on all platforms before submitting updates.

Regards Phillip

**Comment by MockbaTheBorg** [comment]
Awesome guys! No need to be sorry ... things happen.
I will make the changes and give it a try soon.

**Comment by MockbaTheBorg** [comment]
I was able to successfully build after adding the 3 lines to the end of cfg_zeta.asm.
Transferred the .ROM image to a diskette on my Zeta2.
Tried OSLDR /F ROMWMW.BOM and got back a message saying: Obsolete or Invalid BIOS image (BIOS signature)
I am afraid to burn it as it may brick the ZETA2, then I will have to take it apart and reprogram the bios chip, so I would like to know if you guys think it is safe, or if I should wait until you test locally.

Thanks a lot for the assistance.

**Comment by MockbaTheBorg** [comment]
Took a deep breath, opened a beer, a bag of pretzels, went ahead and burned the image.
All works fine.
Thanks a lot guys ... this is awesome .... thank you.

**Comment by wrljet** [comment]
Kinda early on our side of the world for Biers. :-)

**Comment by MockbaTheBorg** [comment]
Never early for a good bier ... :)

**Comment by wrljet** [comment]
True.

Thanks to all who continue to improve this project, BTW.
Bill

**Comment by wwarthen** [comment]
Wow, impressive how fast everyone responded to this!  :-)

I have checked in the corresponding fixes in GitHub.

Thanks,

Wayne
