### ISSUE TITLE
CLRDIR does not wait for response

### ISSUE THREAD

**Issue by GerardWassink** [wwarthen/RomWBW#280]
Hi all,

As delivered, the compact flash card in de RC2014 hardware contains 8 slices.
They are assigned designations from C: to J:
C: through H: contain meaningfull files, whereas I: and J:, afaict, do not.
So I tried to prepare thos slices by using CLRDIR to have them ready to receive files.

This fails, because CLRDIR does not wait for this capital Y but shuts down immediately.

Am I missing something?

Gerard

![CLRDIR_doesnt_wait](https://user-images.githubusercontent.com/14130149/146671673-e235d7f3-1ae3-4a4b-b456-01ae76917522.JPG)

**Comment by b1ackmai1er** [comment]
Hi Gerard,

The most recent version of CLRDIR is V1.2 April 2020.

You could download that and try it.

Best Wishes Phil.

**Comment by GerardWassink** [comment]
Thanks Phil!
Where would I find that version please?
Gerard

**Comment by b1ackmai1er** [comment]
Hi Gerard,

Try this

https://github.com/wwarthen/RomWBW/blob/dev/Source/Images/Common/All/CLRDIR.COM

Regards Phil.

**Comment by GerardWassink** [comment]
Hi Phil,
Tried that version, downloaded it and transferred in to my Z-system on RC2014, but to no avail. Also the specified option -D for debugging output did not seem to work.
AND: it still doesn't wait for reply. See enclosed image...

Gerard

![CLRDIR_1 2_NotWaiting](https://user-images.githubusercontent.com/14130149/146676001-97b8b79b-a76d-48f9-8949-33bcd2194836.JPG)

**Comment by GerardWassink** [comment]
Hi Phil,
Do we also have access to the source?
And if so: is there a proper build stack (for windows) ?
Gerard

**Comment by b1ackmai1er** [comment]
Sorry, I do not know if Wayne has the build stack for it. He should be
online in a couple hours.

The author, Max Scane (mscane) is still active on the retrobrew web site so
you could try contacting him directly.

I had no issues running it with the Debug option.

Regards Phil.

**Comment by GerardWassink** [comment]
Well, Phil, thanks for your responses so far, I'll wait for Wayne to come online (probably will read his reply tomorrow due to time zone difference - NL).
It's a strange thing happening. I cannot imagine no one has seen this before...
It could be my hardware related. I already tuned my clock down a notch to be able to reliably download, but that did not solve this 'problem' either.
Gerard

**Comment by b1ackmai1er** [comment]
Hi Gerard,

I tried to reproduce the issue but had no luck.

To assist Wayne, can you post your system makeup (hardware) and boot screen
information?

Thanks .

**Comment by GerardWassink** [comment]
Yeah sure, here we go:
RC2014:
- Backplane Pro board v1.0
- Compact Flash board v1.3
- 512 ROM / 512 RAM board v1.1
- Z80 CPU board v2.1
- Dual Clock & Rest board v2.1
- Dual Serial board v1.0
- RTC board Rev 1 (2018 by Ed Brindley
- IDE Hard Drive Module v1.0 (no drives attached yet)

At this point my clock is dialed down to 3.6864 MHz to facilitate reliable XM transfers.

For boot screen info see images below.

Gerard

![BootScreen](https://user-images.githubusercontent.com/14130149/146679564-b554ff5c-dac7-4efd-8cd7-cd057fb88201.JPG)

**Comment by wwarthen** [comment]
Hi Gerard,

I apologize for my slow response.  I have been fighting some kind of really nasty cold/flu for the last couple days.  (not Covid by the way).  Thanks for jumping in Phil!

So, Phil is right on all counts.  The CLRDIR utility is provided by Max Scane and I do not have the source for it.  With that said, I have never seen it do what you are describing.  Indeed, it is one of the most used tools in the RomWBW arsenal.  Your hardware  summary is very standard -- many people (including me) with virtually identical configuration.  I am happy to contact Max,  but think it is a long shot that there is a problem with CLRDIR.

Please forgive me for asking questions that probably seem stupid.  Are you experiencing any other anomalies with keyboard input at all?  Are you using the pre-built ROM image?  The date seems to indicate you may be using a customized ROM.  If so, can you send the config file you used?  I see that you are running "CDIR".  I assume you just renamed CLRDIR, which is fine.  What are you using for terminal software?  Is there any chance the software is sending more than just a 0x13 character when you press enter?  I have encountered terminal programs that send 0x13 0x10 for line end.  I have seen that  exact thing cause problems similar to this.

Thanks,

Wayne

**Comment by GerardWassink** [comment]
Hi Wayne,

No problem at all.

You saw me use CDIR, that's because on Phil's suggestion I downloaded version 1.2 and did not want to overwrite the original. Later on I renamed it to CLRDIR12.COM. Unfortunately this did not solve the issue.

I am using TeraTerm now and indeed I am experiencing issues with keyboard input. To be precise, in the CPM environment I can use the BackSpace key as it is intended, but within MBasic I can't. Not sure whether that's an emulation issue tho...

About that ROM: that's the one that was included in Spencer Owen's delivery, so I do not have a config file at hand.

I will try to investigate what TeraTerm is sending when the ENTER key is pressed and let you know...

Gerard

**Comment by GerardWassink** [comment]
I think I found the culprit, TeraTerm was set to CR+LF:
![afbeelding](https://user-images.githubusercontent.com/14130149/146752624-bf814968-6985-4c7a-9ce4-6feedb0ffa81.png)

I changed it to only send a CR and now it works:
![afbeelding](https://user-images.githubusercontent.com/14130149/146752700-b6c255d7-736a-4716-bf59-428d78cfbc98.png)

Thanks!

**Comment by GerardWassink** [comment]
Can I close the issue, or do we leave that up to the owner of the repository?

Gerard

**Comment by wwarthen** [comment]
Glad you found the problem.

Yes, I think you can close the issue yourself.  If you have trouble doing it, let me know.

Thanks,

Wayne

**Comment by GerardWassink** [comment]
Thanks Wayne, for the assistance solving this issue.
Gerard
