### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by EtchedPixels** [wwarthen/RomWBW#282]
Building RCZ180 nat trundles happily along until

Making Blank HD1024 of size 8192k
8192+0 records in
8192+0 records out
8388608 bytes (8.4 MB, 8.0 MiB) copied, 0.0100127 s, 838 MB/s
0000000 e5e5 e5e5 e5e5 e5e5 e5e5 e5e5 e5e5 e5e5
*
0800000
Generating fd144_cpm22.img
copying system ../CPM22/cpm_wbw.sys to fd144_cpm22.img
  copying directory d_cpm22/u0
     d_cpm22/u0/ASM.COM
     d_cpm22/u0/DDT.COM
     d_cpm22/u0/DUMP.COM
     d_cpm22/u0/ED.COM
     d_cpm22/u0/HELP.COM
     d_cpm22/u0/HELP.HLP
     d_cpm22/u0/LIB.COM
     d_cpm22/u0/LINK.COM
     d_cpm22/u0/LOAD.COM
     d_cpm22/u0/MAC.COM
     d_cpm22/u0/PIP.COM
     d_cpm22/u0/RMAC.COM
     d_cpm22/u0/STAT.COM
     d_cpm22/u0/SUBMIT.COM
     d_cpm22/u0/XSUB.COM
     d_cpm22/u0/ZSID.COM
fd_cpm22.txt
  copying files from fd_cpm22.txt
     d_cpm22/ReadMe.txt
     ../../Binary/Apps/Assign.com ../../Binary/Apps/assign.com
cpmcp: can not create 00assign.com: file already exists
make[2]: *** [Makefile:71: fd144_cpm22.img] Error 1
make[2]: Leaving directory '/bulk/home/alan/Z80/RomWBW/Source/Images'
make[1]: *** [../Tools/Makefile.inc:132: all] Error 2
make[1]: Leaving directory '/bulk/home/alan/Z80/RomWBW/Source'
make: *** [Makefile:3: all] Error 2

**Comment by wwarthen** [comment]
Hi Alan,

Sorry about this.

I have not been able to recreate the problem.  The build seems fine on my local system and the error does not occur on the automated Ubuntu build on GitHub.

The error indicates that ASSIGN.COM is already in the floppy image being created.  Doesn't make sense according to the log.

The Makefile is not very good at handling a "rerun".  Ideally, you should use "make clobber" at the root before running a new build.  Using "make clean" should be OK as well, but "make clobber" is more thorough.

I'm not sure what else to suggest at this point.

Thanks,

Wayne

**Comment by wwarthen** [comment]
Oh, I just realized that the log is indicating you have two copies of assign.com with different case in your Binary/Apps directory.  I'm not sure what would cause that, but it gives me something to look for.

Thanks,

Wayne

**Comment by EtchedPixels** [comment]
I'll have a dig as well. That kind of makes sense - on Windows they'd overwrite one another and not be noticed.

**Comment by wwarthen** [comment]
Just to let you know, I am coming up empty on this.  I have searched everywhere to find a place where assign.com might be getting generated with different case and just don't see it.  Is there any chance you had contents from an older source build?

Thanks,

Wayne

**Comment by EtchedPixels** [comment]
make clobber does indeed do the trick.

Thanks

**Comment by wwarthen** [comment]
Very happy to hear you got it working Alan.  I will review the Unix build documentation -- I don't think it is clear enough about the rerun deficiencies and the use of "make clobber".
