### ISSUE TITLE
(Q) A new Release?

### ISSUE THREAD

**Issue by feilipu** [wwarthen/RomWBW#300]
Just realised it's about (over) 2 years since the last 3.0(.1) release.

Any thoughts about when you might do a new one?

**Comment by wwarthen** [comment]
I suppose a 2 year release cadence is pushing it a bit!  😀  I'm afraid that I am easily distracted by new feature requests and new hardware to support.  The current development snapshot has been very stable.  I do need to update some of the documentation.  I will try to get something out in the near future.

I will leave this as an open issue to remind me until it is done.

Thanks.,

Wayne

**Comment by feilipu** [comment]
Perhaps a stable release would be timely before rewriting terminal code to seperate keyboard and display?
New start in 2023!

**Comment by wwarthen** [comment]
> Perhaps a stable release would be timely before rewriting terminal code to separate keyboard and display? New start in 2023!

I absolutely agree.  I have already started on the documentation.

-Wayne

**Comment by wwarthen** [comment]
All done!  See [Release v3.2.0](https://github.com/wwarthen/RomWBW/releases/tag/v3.2.0).

-Wayne

**Comment by b1ackmai1er** [comment]
Kudos Wayne, Awesome work.

**Comment by MorfeoMatrixx** [comment]
Brilliant ! Thank you Wayne and collaborators for this colossal task !

Regards,
Jose Luis Collado
(morfeo.matrixx)

**Comment by wrljet** [comment]
Amazing, as always!

Bill
