### ISSUE TITLE
(Q) - freeRTOS context switch qualification

### ISSUE THREAD

**Issue by feilipu** [wwarthen/RomWBW#301]
I'm working through some freeRTOS examples, and I've struck something that I thought had been working, but now isn't.
My problem is that calls into HBIOS seem to get stuck, when waiting for character input.

If you remember, we did a few things to secure that context switches didn't happen during the time that a call was currently in HBIOS, and therefore the wrong memory bank was switched in to handle the interrupt.

We created a HBIOS MUTEX, to ensure that only one call into HBIOS could be active. I don't think that's changed or broken.

To qualify a context switch we checked both that the user TPA is switched in, and that the stack pointer is not in the HBIOS buffer area. Both of these things are represented [below](https://github.com/feilipu/z88dk-libraries/blob/master/freertos/source/include/FreeRTOSBoardDefs.h#L237).

```asm
#define configSWITCH_CONTEXT()                                  \
    do{                                                         \
        __asm                                                   \
            EXTERN BBR                                          \
            in0 a,(BBR)                                         \
            xor 0xF0                ; BBR for user TPA          \
            jr NZ,ASMPC+9                                       \
            ld hl,0x0100                                        \
            add hl,sp               ; Check SP < 0xFFnn         \
            call NC,_vTaskSwitchContext                         \
        __endasm;                                               \
    }while(0)
```

Anyway, I'm striking a problem when calling `getchar()` [from this example](https://github.com/feilipu/z88dk-libraries/blob/master/freertos/demo/TaskStatus/TaskStatus.c#L78). I've changed the code for the [serial interface to not block](https://github.com/z88dk/z88dk/commit/2df99e83ff096190106c0ae4a80a9e7833759a59) inside HBIOS, and this helps but doesn't solve the problem.

### Q

So, I'm not totally sure that the __BBR__ for user TPA is actually __`0xF0`__.
Could you please confirm that matching specifically `0xF0` is the most effective method to match only the user TPA?

Thanks in advance.
P.

---

### Wrong A

Perhaps hitting `HL` and not preserving it is causing the issue...? To check now.
No... that's dumb. The context is preserved and restored around the `configSWITCH_CONTEXT`.
Need to look further.

**Comment by wwarthen** [comment]
> ### Q
> So, I'm not totally sure that the **BBR** for user TPA is actually **`0xF0`**.
> Could you please confirm that matching specifically `0xF0` is the most effective method to match only the user TPA?

For a Z180 with 512K ROM & 512K RAM (normal setup), then BBR=0xF0 is synonymous with user TPA being mapped to low 32K.

Based on your description, it sounds like interrupts might be suppressed while waiting for the character.  Is that possible?

Thanks,

Wayne

**Comment by feilipu** [comment]
Thanks. Helps so much to get clarification.

> It sounds like interrupts might be suppressed while waiting for the character. Is that possible?

Things should be running normally, unless a call is inside HBIOS, then the System Tick ISR will recognise that a) the BBR is not in USR  TPA, or b) the SP is set within the HBIOS call stack area (top page). If either of these things happen, then the System Tick will reset the timer, and exit. Of course the System Tick will only be entered if interrupts are enabled (which they should be). Otherwise in the normal case a Tick increment will happen and a context switch opportunity happens.

I have [just resolved one issue](https://github.com/feilipu/z88dk-libraries/commit/779a69e6ccb9a94adedd49db94f6e426723ec07b?diff=split), where the call to increment the System Tick was not properly protected by the SP location check. I just fixed that, and at the same time simplified things a little.

This has made things incrementally better. But, I'm still fishing to find the underlying problem with `getchar()`.

**Comment by wwarthen** [comment]
Odd.  Sorry I don't have any immediate thoughts.

-Wayne

**Comment by feilipu** [comment]
I'm still looking, but will close this as it's sure to be on my code base. Thanks again.
