### ISSUE TITLE
RomWBW Digital I/O Input at Startup

### ISSUE THREAD

**Issue by wwarthen** [wwarthen/RomWBW#315]
Read Digital I/O settings at startup and use them to determine boot behavior.

Current proposal is:

Switch 0: Enable Autoboot
Switch 1: Swap Serial 0 &1
Switch 2-4: Select boot disk unit (0-7)
Switch 5-7: Select boot slice number (0-7)

**Comment by wwarthen** [comment]
Alan pointed out that a switch to choose between serial console and physical kbd/video console would be very useful.  That makes a lot of sense.

**Comment by wwarthen** [comment]
Here is a proposed panel definition:

<img width="325" alt="Panel" src="https://user-images.githubusercontent.com/2546153/222991807-d2f9007d-5872-4c99-b5cd-ee7fc8b32e1b.png">

**Comment by wrljet** [comment]
Cool!

**Comment by b1ackmai1er** [comment]
Love it. For me I would prefer normal/safe mode over sec/pri. Very nice
concept.

Regards Phil

**Comment by wwarthen** [comment]
> For me I would prefer normal/safe mode over sec/pri.

I did think about that.  At present, the switches would be implemented in the ROM Loader.  That is too late in the boot process to handle normal/safe boot.

What about using a "special" combination of switches to trigger a safe boot?  Something like all switches set (0xFF)?

-Wayne

**Comment by b1ackmai1er** [comment]
No, go with what you've got. I Like it.

**Comment by wwarthen** [comment]
This issue has been addressed in commit f346209

**Comment by MorfeoMatrixx** [comment]
Brilliant ! Thanks Wayne for another ROMWBW goody !
Regards, JL.

**Comment by wwarthen** [comment]
By way of closing the loop here, I have made a slight change to the front panel layout.  The intention is to get the console stuff and the boot stuff grouped correctly.

<img width="325" alt="Panel2" src="https://user-images.githubusercontent.com/2546153/232353168-f15ce283-7dce-4d95-82e1-78334306c957.png">

Happy to get further comments.

-Wayne
