### ISSUE TITLE
Initializing UART4 board I/O port clash

### ISSUE THREAD

**Issue by b1ackmai1er** [wwarthen/RomWBW#325]
Hi Wayne, 

I had an issue that the CTC  on my ECB-VGM board was generating a 40Hz timer tick instead of 60Hz.
During that investigation I identified that my CTC at base port $cc was being written to by another driver.
As shown in the disassembly, both the uart driver and ctc are writing to uart channel 3.

I have submitted an update so that when UART4 is disable, this write no longer takes place.
However, I do not think this is safe practice to have UART4 enabled by default - users who do not have a 
UART4 board have no way of knowing that setting up another device in this address space may be a problem.

UART DRIVER:
```
0080+  10FC             UART_PREINIT:
0081+  10FC             ;
0082+  10FC             ; INIT UART4 BOARD CONFIG REGISTER (NO HARM IF IT IS NOT THERE)
0083+  10FC             ;
0084+  10FC 3E 80       	LD	A,$80			; SELECT 7.3728MHZ OSC & LOCK CONFIG REGISTER
0085+  10FE D3 CF       	OUT	(UART4BASE+$0F),A	; DO IT
```

CTC DRIVER:
```
0186+  57A7 3E D7       	LD	A,CTC_TIMCFG		; TIMER CHANNEL CONTROL WORD VALUE
0187+  57A9 D3 CF       	OUT	(CTC_SCLIO),A		; SETUP TIMER CHANNEL
0188+  57AB 3E E9       	LD	A,CTC_DIVLO & $FF	; TIMER CHANNEL CONSTANT
0189+  57AD D3 CF       	OUT	(CTC_SCLIO),A		; SET TIMER CONSTANT
```

**Comment by wwarthen** [comment]
Yup, good catch.  My assumption that it would do no harm is absolutely invalid.  After I merge your fix, I will close this issue.

Thanks!

Wayne

**Comment by wwarthen** [comment]
OK, I have merged your fix.  Will close this now.

-Wayne
