### ISSUE TITLE
Problematic CTC divisor check

### ISSUE THREAD

**Issue by b1ackmai1er** [wwarthen/RomWBW#327]
Hi Wayne,

This check in the CTC driver is quite problematic with alternate CTCOSC values.

```
  #IF ((CTC_DIVHI * CTC_DIVLO * CTC_PRESCL * TICKFREQ) != CTCOSC)
	.ECHO "COMPUTED CTC DIVISOR IS UNUSABLE!\n"
	!!!
  #ENDIF
```

For example 
```
CTCOSC .SET 3579545
TICKFREQ .SET 60

CTC DIVISOR: 59659, HI: 256, LO: 233
COMPUTED CTC DIVISOR IS UNUSABLE!
ctc.asm line 0132: unrecognized directive.            (!!!)
```

If we look at the values it is comparing  ...

```
  #IF ((CTC_DIVHI * CTC_DIVLO * CTC_PRESCL * TICKFREQ) != CTCOSC)
	.ECHO "COMPUTED CTC DIVISOR IS UNUSABLE!\n"
	.echo ((CTC_DIVHI * CTC_DIVLO * CTC_PRESCL * TICKFREQ)
	.echo "\n"
	.echo	CTCOSC
	.echo "\n"
	!!!
  #ENDIF

CTC DIVISOR: 59659, HI: 256, LO: 233
COMPUTED CTC DIVISOR IS UNUSABLE!
3578880
3579540
ctc.asm line 0136: unrecognized directive.            (!!!)
CTC occupies 234 bytes.

```
;

It's basically identifying the CTC divisors do not generate a perfect tick frequency.

I'm thinking a warning would be more appropriate rather than a build failure.

To get this to build I have to update the CTCOSC to 3578880, which generated the same divisors,

**Comment by wwarthen** [comment]
OK, I see what you are saying.  The assertion insists on a divisor that works exactly.  I agree with you -- a warning makes more sense in this situation.  I will make that change.

Thanks,

Wayne

**Comment by wwarthen** [comment]
OK, the assertion is now a warning.  Closing this issue.

Thanks,

Wayne
