### ISSUE TITLE
V3.3.3dev7 - Small typo in ROMWBW System Guide P.60 (maybe?)

### ISSUE THREAD

**Issue by MorfeoMatrixx** [wwarthen/RomWBW#345]
Hi Wayne, maybe a small typo in page 60, **SYSSET** Subfunction 0xF4 – Set Front Panel LEDs (PANEL), I think entry Parameter B should read **F9** instead of **F8** (F8 invokes **SYSGET** function). I didn´t know how you prefer receiving feedback on documentation and manuals, so I opened this as an issue following my complete lack of experience using Github; please let me know which is your prefered method.

Thanks again for your outstanding work and support.

Regards, Jose Luis.

**Comment by wwarthen** [comment]
Hi @MorfeoMatrixx,

I am thrilled to get this kind of bug report.  Documentation is very important.

Will fix in upcoming check-in today.

Thanks!

Wayne

**Comment by wwarthen** [comment]
This is now fixed in commit e320025.

Thanks!
