### ISSUE TITLE
Additional disks in the combo images?

### ISSUE THREAD

**Issue by rprouse** [wwarthen/RomWBW#347]
Is there interest in including additional non-os disks in the multi-image? It already contains a WordStar 4 disk, but in my fork I also added several disks of programming tools. If there is interest, I would be happy to create a PR.

I added the following disks,

| Disk      | Description                                                                                                                 |
| --------- | --------------------------------------------------------------------------------------------------------------------------- |
| d_z80asm  | [Z80ASM](http://www.s100computers.com/My%20System%20Pages/IBM%20Keyboard/z80asm%20(SLR%20Systems).pdf) by SLR Systems                                                                                                       |
| d_aztecc  | [Aztec C](https://www.aztecmuseum.ca/) II compiler v1.06D                                                                   |
| d_hitechc | [HI-TECH Z80 CP/M C compiler](https://techtinkering.com/2008/10/22/installing-the-hi-tech-z80-c-compiler-for-cpm/) V3.09    |
| d_tpascal | [Turbo Pascal](https://techtinkering.com/2013/03/05/turbo-pascal-a-great-choice-for-programming-under-cpm/) Compiler v3.01A |
| d_bascomp | Microsoft Basic-80 Compiler v.5.30a                                                                                         |
| d_fortran | Microsoft Fortran-80 Compiler v.3.44                                                                                        |
| d_games   | Games, Infocom games, Nemesis and Dungeon Master                                                                     |

I do not know the copyright status of these disks (or the disks that you include now) so that might be an issue. I consider them all to be abandonware and downloaded most from Archive.org.

Let me know if you want a PR, or feel free to close the issue if it isn't the direction you want to go in.

**Comment by wwarthen** [comment]
I would be very happy to have some more disk images in RomWBW.  The entire disk image building process was designed to make it straightforward to hold more disk images.  There are a few things I would ask though.

1. Do not add any more slices to the existing "combo" images.  May people are using 64MB disk media and more slices will cause the image to not fit for them.  It is pretty simple for individual users to concatenate more slices as they want.  I tried to make that process clear in the documentation.
2. Any new disk images should be added by putting the individual files into a directory tree that is then turned into a disk image by the build process.  You will notice that multiple disk formats are created and doing it this way facilitates that.
3. I would appreciate seeing a README.TXT or similar file included in new disk images that explains what the disk contains, where it came from, etc.  I know that the existing disk images do not all have this, but I am trying to work toward that for all disk images.

Thanks!

Wayne

**Comment by rprouse** [comment]
Thanks for the guidance. I've already made the changes in a branch on my fork, so I it shouldn't take too long to get into a form that will work.

**Comment by rprouse** [comment]
Closed with #348
