### ISSUE TITLE
SC126 support seems broken for RTC

### ISSUE THREAD

**Issue by EtchedPixels** [wwarthen/RomWBW#36]
Unless I am missing someting the dsrtc code will write zero bits to the non RTC bits of the RTC bit bang register. On the SC126 two of those are \CS for the SPI devices so you will drive both device card selects which I wouldn't expect ends very well, especially as those bits then get left hanging selected.

Also the SC126 is different to the SC111 (aka current RC2014 Z180 config) in that it has this register difference and also register 0x0D, so it seems odd to make it the same platform id.

**Comment by b1ackmai1er** [comment]
Regarding dsrtc, I am also playing with bit 4 port 70h on the SBC V2 to control the cpu clock speed. My understanding us that accessing the RTC will also reset the CPU speed back to normal when accessed. While this feature may not become a part of the SBC V2 in future it would be good to put some mechanism in place to protect the non-dsrtc bits.

**Comment by wwarthen** [comment]
> Unless I am missing someting the dsrtc code will write zero bits to the non RTC bits of the RTC bit bang register. On the SC126 two of those are \CS for the SPI devices so you will drive both device card selects which I wouldn't expect ends very well, especially as those bits then get left hanging selected.

Yes, that is not going to work well.

> Also the SC126 is different to the SC111 (aka current RC2014 Z180 config) in that it has this register difference and also register 0x0D, so it seems odd to make it the same platform id.

I am actually trying to avoid the proliferation of platform id's at this point.  They are causing a crazy amount of long conditionals in the source.  The existing driver already implements a constant value for DSRTC_RESET which defines the quiescent state of the latch.  Would be straightforward to add another mode value for the driver that would be used for the SC126 and just uses a happier DSRTS_RESET constant.

A similar approach can be used for the 0x0D port.  It is analogous to the standard RC2014 digital output port.

I am about to build an SC126 now and will work on these software changes subsequently.

**Comment by wwarthen** [comment]
> Regarding dsrtc, I am also playing with bit 4 port 70h on the SBC V2 to control the cpu clock speed. My understanding us that accessing the RTC will also reset the CPU speed back to normal when accessed. While this feature may not become a part of the SBC V2 in future it would be good to put some mechanism in place to protect the non-dsrtc bits.

I need to think about this a bit.  The immediate problem with protecting these latch bits is that they cannot be read (write only), so there is no way to check the current value of the port before updating it.  RomWBW could implement a shadow copy of the register value, but that is only valuable if all writes to this port are under the control of RomWBW.  I'm not sure that is a reasonable expectation.  Definitely would not be ideal for DSRTC accesses to modify the operating speed of the system though, so needs to be resolved somehow.

**Comment by EtchedPixels** [comment]
The problem is that any OS that can't use ROMWBW calls can't tell them apart, and in this case there doesn't even seem to be a way to tell them apart by making ROMWBW calls before switching OS. It's doubly nasty when getting it wrong potentially blows stuff up. Is there a call/way you can think to tell them apart that I am missing?

0x0C isn't a constant. It depends which ROM you booted off and the only way you can find out that I can see is to know what bytes you can peek at from RAM in each ROM to work out which is your current ROM (or at least has matching version string or somesuch).

As an aside I think the SD select is actually an SC126 design bug - it should have fed them into a 2->4 MUX even if it only used two lines. Now I look harder I don't even see what stops it coming up wrongly at power up. The doc I have says the 273 will reset to 0 so pull both SPI selects low.

**Comment by wwarthen** [comment]
I believe I have corrected the initial, primary issue.  Specifically, the quiescent state of the RTC latch port for SC126 will keep /CS1 and /CS2 inactive (high).

I acknowledge there are a couple additional issues being raised here:
1. Maintaining a dynamic shadow copy of the RTC latch port.
2. Allowing an HBIOS caller to determine the RTC hardware type.

For now, I will leave this issue open until I can resolve these additional items.

Thanks,

Wayne

**Comment by wwarthen** [comment]
I have implemented a shadow register for the RTC port and adjusted the RTC, SD, and SPK drivers to share the port cleanly.  In other words, they do not cause side effects to bits they do now own in the RTC port.

I am still thinking about options for the problem of allowing an HBIOS caller to unambiguously differentiate some hardware configurations that currently share a platform ID.  I am  going to find a way to resolve that, but it may take a bit more time because it is more of any architectural issue.  Since the primary original issue is resolved, I am going to go ahead and close this issue.

**Comment by wwarthen** [comment]
As a follow-up to this issue, I have ultimately decided to go ahead and give SC126 a separate platform id.  This has been implemented in the latest check-in to the master branch.
