### ISSUE TITLE
XON/XOFF support

### ISSUE THREAD

**Issue by pavelzampach** [wwarthen/RomWBW#361]
Add, please, XON/XOFF support to serial port drivers.

**Comment by wwarthen** [comment]
Hi @pavelzampach,

To be totally honest, this would be a huge amount of work.  There are more than a dozen serial drivers in RomWBW that would need to be enhanced.  Thus far, you are the only person that has requested this feature, so it is hard to prioritize.

Could you share your use case?  If you are trying to do something that many others will benefit from, I might be willing to work on this.

Thanks,

Wayne

**Comment by wwarthen** [comment]
Since I have not received a response, I am going to go ahead and close this issue.

-Wayne
