### ISSUE TITLE
I/O Wait States on Z180

### ISSUE THREAD

**Issue by EtchedPixels** [wwarthen/RomWBW#37]
The ROMWBW code does the following to set up the Z180 wait states

	; SET DESIRED WAIT STATES
	LD	A,0 + (Z180_MEMWAIT << 6) | (Z180_IOWAIT << 4)
	OUT0	(Z180_DCNTL),A

So Z180_IOWAIT is 0-3 meaning 1-4 wait states

In CFG_RCZ180 it says

Z180_IOWAIT	.EQU	1		; IO WAIT STATES TO INSERT (0-3)

However that actually inserts two wait states as the real range is 1-4. Two seems reasonable so is this just a documentation glitch ?

**Comment by wwarthen** [comment]
Yes, the comment could be clearer.  By "insert", I was intending to convey that this number is the additive wait states beyond the processor minimum.  I will improve the comment in the next release, but will leave this issue open until that is committed.

Thanks!

**Comment by wwarthen** [comment]
OK, I changed the comment on this setting in all the config files.  I think the meaning is now clear.  Will close this issue for now.  Feel free to reopen it if I have missed the boat.
