### ISSUE TITLE
CLS returns capital H char on pigfx terminal

### ISSUE THREAD

**Issue by Alex-Kw** [wwarthen/RomWBW#384]
I just upgraded from RomWBW 3.0.1 to 3.4. I have a macro on my keyboard which types CLS and a carriage return, which cleared the screen. Now, that macro as well as just typing CLS and return just returns a capital "H" instead of clearing the screen.

Thanks for all the awesome updates and work. Cheers.

**Comment by wwarthen** [comment]
Hi @Alex-Kw,

This sounds like the pigfx is sending data faster than the serial port interrupt handler can handle.  There have been small changes to the interrupt handling code between these versions.

Please tell me which serial port hardware you are using.  ACIA?  SIO?  or something else?

Thanks,

Wayne

**Comment by wwarthen** [comment]
Sorry, I got stuck on the idea that it was related to the keyboard macro, but I now understand that it is happening even if you just type it manually.

The `CLS` command is only available on some of the OSes.  Which OS are you using?  I confirmed that entering `CLS` on Z-System (ZSDOS + ZCPR 1), NZCOM, and ZPM3 worked (cleared the screen correctly).  I would not expect it to work on CP/M 2.2 or CP/M 3.

Thanks,

Wayne

**Comment by Alex-Kw** [comment]
Thanks Wayne. I'm only expecting it to work in ZPM3, so I'll ensure I'm absolutely booting the right slice or even try some of the others. I'll circle back and let you know for sure.

**Comment by Alex-Kw** [comment]
Definitely was using ZPM3, ZSDOS also exhibits the same behavior after the upgrade to 3.4.0.

Let me know if there's anything of use I can check. My MBASIC clear screen command still works fine, "PRINT CHR$(12);" and a CR clears the screen well.

**Comment by wwarthen** [comment]
Hi Alex,

I think I may have found an explanation for what is happening.  I went back and reviewed the escape sequence emitted to clear the screen under ZPM3 in v3.0.1 vs. v3.4.  They changed between these versions:

Old: `<esc>[2J<esc>[H`
New: `<esc>[;H<esc>[J`

Under ZPM3, the clear-screen escape sequence is determined by the TCAP.Z3T file.  This file was changed in commit 63a3159 and the comments were:

>Updated tcap.z3t for ZPM3 slice.  Previous definition was VT-525.  New definition is specifically VT-100.
Credit to Marco Maccaferri for all of this.

In theory, the new TCAP definitions were supposed to be an improvement.

The old and the new escape sequences both work in my terminal emulator and should be OK according to the DEC terminal standards.  However, I suspect that pigfx does not like the ";" in the new escape sequence, aborts processing the escape sequence, and prints the trailing 'H'.

I don't know of a tool to edit the TCAP.Z3T files.  You would probably need to do it with a hex editor.  The `ZAP` application included with RomWBW would work.  Note that the `TCVIEW` application included with RomWBW can be used to view a TCAP.Z3T file.

NZCOM (slice 2) will behave the same as ZPM3.  However, ZSDOS (slice 1) should be sending `<esc>[2J`.  I would expect that to work.

Thanks,

Wayne

**Comment by Alex-Kw** [comment]
Wayne,

Thank you! You are correct in your expectation of ZSDOS, I must have been on NZCOM last night. 

I can be happy with this! I'll either edit the TCAP.Z3T file(s) as appropriate, or see if I can just fix and recompile PiGFX to accept both escape sequences.

Cheers,
Alex

**Comment by wwarthen** [comment]
Glad we have an explanation for this.  It is good to know about this because others may encounter a similar problem.

Thanks,

Wayne
