### ISSUE TITLE
diskdefs and combo image

### ISSUE THREAD

**Issue by rampa069** [wwarthen/RomWBW#386]
Hi.

 Congratulations for your work in romWBW!

  I am implementing a RC2014 in FPGA (almost working) and have problems with disk images. seems diskdefs in the tools directory is a bit obsolete (or i am missing something)

 I can transfer to images as turbopascal ord ws4 without problems (but theese images are not working on the machine) but cannot with RCZ80_combo or hd512_cpm22.img. (both working on the machine)

 is this a diskdefs problem?

**Comment by rampa069** [comment]
my fault... It works with the cpmtools binary in the Tools directory.

**Comment by wwarthen** [comment]
Hi @rampa069,

Glad to hear you got it working.  I'm not sure I fully understand what the problem was.  If you have any further problems, let me know.

Thanks,

Wayne

**Comment by rampa069** [comment]
I'm using  OSX and i use cpmtools from brew (repository).

 With the system cpmtools, didn't work. Was looking at the makefiles and look they were using an "embebbed" cpmtools. used the one in the Tools directory and all worked.

**Comment by wwarthen** [comment]
OK, thanks!
