### ISSUE TITLE
Doc Folder Minor Reorg (Trivial)

### ISSUE THREAD

**Issue by kiwisincebirth** [wwarthen/RomWBW#395]
Suggestion for cosmetic improvement

The `Doc` folder of this project has become a little large, and would benefit from a couple of sub folders. If you like I could create a Pull request for the following 2 new folders

CPM - Clearly anything to do CPM or any of the many derivatives
Language - Anything to do with a programming language

Apart from the above I cant suggest any further changes since the remaining files fall into a Misc category, and any organisation would be better suited to a main project contributor. However my only suggestion would be a Hardware folder, since there seem to be alot of small documents (including in Contrib folder) that describe an aspect of hardware.

**Comment by wwarthen** [comment]
Hi @kiwisincebirth,

Yes, this is a good idea.

The only tricky part is that there are references to the location of these documents scattered about the distribution.  To do this correctly, all of the RomWBW source documents (in Source\Doc) and all of the ReadMe.doc files throughout the project will need to be reviewed and adjusted as needed.

If you are OK with doing all of that, feel free to do a Pull Request.

Thanks!

Wayne

**Comment by kiwisincebirth** [comment]
@fixit9660 - I will work on creating a "CPM" folder, if you want to do a "Language" folder I don't there should be much conflict.

> all of the RomWBW source documents (in Source\Doc) and all of the ReadMe.doc files throughout the project will need to be reviewed and adjusted as needed.

From what I can see the $doc_root$ is the once that Have to be corrected. Most other I see just refer to the document by name (sometime folder) and just a wording change to refer to the folder.

Also a readme.txt change in the /Doc folder itself, to move content into a new Readme in the new subfolder

**Comment by kiwisincebirth** [comment]
I will work on Language folder

**Comment by kiwisincebirth** [comment]
I have done the main changes. If there other files that need moving let me know. I think I did the main ones. I dont know the history of the Contrb folder but two files could be moved. ZSystem.txt and Microsoft NASCOM Basic.docx

Also I found 2 (mostly identical) __The__ Cowgol Language files - not sure why they are 2 - one has a couple of extra pages.

**Comment by wwarthen** [comment]
Awesome.  Thank you @kiwisincebirth.  This is crazy weekend for me, so please give me a little time to do a quick review and merge your changes.

Greatly appreciate the contribution!

Thanks,

Wayne

**Comment by wwarthen** [comment]
Hi @kiwisincebirth,

Very sorry for the delay.  I normally get to these merge requests much faster, but this weekend was a lost cause.

You are correct that there are duplicate Cowgol documents out there.  I will remove one of them.

Your changes look great and it appears you have thoroughly updated appropriate references.  I am merging your changes now.  Note that you will see another check-in from me in a few minutes because I need to do the normal PDF documentation regeneration.

Thank you for you help with this!

Wayne

**Comment by wwarthen** [comment]
Pull Request #396 has been merged and resolves this issue.  Closing the issue.

Thanks,

Wayne
