### ISSUE TITLE
Minor Doc error in RomWBW ROM Applications

### ISSUE THREAD

**Issue by stickbreaker** [wwarthen/RomWBW#401]
The ROMWBW ROM Applications ver 3.4 and 3.5 are not quite up to date for the Monitor Help.

The document does not contain an mention of the U command.

Chuck.

**Comment by wwarthen** [comment]
Thank you @stickbreaker.

This document (and the RomWBW Applications document) are being overhauled by Martin R right now.  I will pass this along to him.

Thanks, Wayne

**Comment by wwarthen** [comment]
This has been fixed with commit e1e4855.  Closing the issue.

Thanks, Wayne
