### ISSUE TITLE
BEEP in HBIOS

### ISSUE THREAD

**Issue by pavelzampach** [wwarthen/RomWBW#402]
Please, add access to BEEP routine via HBIOS sound services.

**Comment by wwarthen** [comment]
Sure.  I will get that done in the next few days.

-Wayne

**Comment by wwarthen** [comment]
@pavelzampach,

I have added a BEEP function in the Sound API in RomWBW Development Snapshot v3.5.0-dev.56.  The function is documented in the RomWBW System Guide document.

I apologize for the delay getting this done.  I have been very busy.

I will leave this issue open for a few days in case there is further related feedback.

Thanks, Wayne

**Comment by wwarthen** [comment]
I am going to close this issue now.  If there are furhter questions or issues, please reopen.

Thanks, Wayne
