### ISSUE TITLE
Support for Extreme Kits Pico SD IDE interface

### ISSUE THREAD

**Issue by zomgugoff** [wwarthen/RomWBW#404]
Any chance support for these SD IDE adapters could be added?

https://github.com/ExtremeElectronics/Pico-SD--IDE-interface--for-Rc2014

I picked up one of these kits about a year ago and have yet to be able to use it. I'm still getting the hang of RC2014 but I think the strange limitation on the IO port selection is a problem. It only allows for selecting ports in increments of 8 starting at 0. I suspect that, once upon a time, this did work as the repo contains file for use with RomWBW.

**Comment by wwarthen** [comment]
I will take a look.  You see support in the repo because I do currently support Spencer's RC2014 version of this board.  I don't know offhand if there is a difference between the one published by @ExtremeElectronics or not.  I need to look at it.

Thanks, Wayne

**Comment by ExtremeElectronics** [comment]
Yes it is the same board. Bear with me its been a while :) 

I did get it to work with RomWbW (from memory), but it needs a different CPM format from standard (RC2014 CF) replacing the files on the SD card. I "Think" there is mention of this somewhere on the RC2014 pages. 

I don't remember having any I/O clashes, as the I/O follows the existing CF card for the RC2014 which I believe works with ROMWBW

**Comment by ExtremeElectronics** [comment]
RomWBW sd card files... 
https://github.com/ExtremeElectronics/Pico-SD--IDE-interface--for-Rc2014/tree/main/ROM%20WBW%20SD

**Comment by zomgugoff** [comment]
I assumed the I/O port was an issue because it doesn't appear to use the same port as the CF module. The device isn't detected on boot at all.

**Comment by wwarthen** [comment]
Thanks @ExtremeElectronics.

@zomgugoff,

It sounds like it should work with the current release of RomWBW without any changes to RomWBW.

It does require that the SD Card be configured for RomWBW.  Specifically, you need to copy the RomWBW disk image onto the card.  Copy the hd1k_combo.img file from the Binary folder of the RomWBW distribution to the root of the SD Card.  Then update the RC2014.ini file to point to it like this:

```
idefile = "hd1k_combo.img";
```

I guess the only other issue would be if you are using an older release of RomWBW.  You should be using v3.4 or the development snapshot.  As I recall, under v3.4, the SD Card may not be recognized at power on because it is not ready for access fast enough.  Pressing the reset button to reboot should take care of that.  The development snapshot has added intelligence to detect the board and wait for it to be ready, so it does not have that issue.

Does that help?

Thanks, Wayne

**Comment by wwarthen** [comment]
Port 0x20 sounds right.  I don't know offhand what the device will do if
the files are not correct.  I don't have time to test right now, but will
try that scenario later today.

Thanks, Wayne

**Comment by wwarthen** [comment]
@zomgugoff,

As I started my testing, I realized that port 0x20 is **not** correct.  This device presents as an IDE device.  For RC2014 IDE devices are normally found at port 0x10 which is where RomWBW is looking for it.  This could explain your problem.

By the way, it does appear that RomWBW will detect the module even if there is no SD Card inserted at all.

Thanks, Wayne

**Comment by zomgugoff** [comment]
That's where my suspicion about the port is coming from. The jumpers on the board only allow for ports in increments of 8. Unless I'm misunderstanding, the module can't be set to 0x10.

**Comment by ExtremeElectronics** [comment]
0x10 HEX = 16 Decimal ?

**Comment by zomgugoff** [comment]
Aha. I was misunderstanding. Apparently I need to check hardware and software.

I realize I've sort of gone off-topic here. I appreciate both of your help, despite that. Thank you.

**Comment by wwarthen** [comment]
😀Please just reply to let us know if you get it working.

Thanks, Wayne

**Comment by ExtremeElectronics** [comment]
No problems, we have all been there :) 
Derek

**Comment by zomgugoff** [comment]
Just a minor update: It turns out the module is showing up in the detected hardware list. I'll continue hardware inquires on the repo for the module.

**Comment by zomgugoff** [comment]
@ExtremeElectronics I posted 2 issues on (what I presume is) your Git repo. I haven't seen any reply. I wasn't sure if that's something you check as it had no prior issues listed.

**Comment by zomgugoff** [comment]
This has been resolved [here](https://github.com/ExtremeElectronics/Pico-SD--IDE-interface--for-Rc2014/issues/2#issue-2404371262).

In a nutshell, user error involving a short along the edge of the Pi Pico.

**Comment by wwarthen** [comment]
Glad you got it resolved @zomgugoff.
