### ISSUE TITLE
Improved Doc for Real Time Clock

### ISSUE THREAD

**Issue by kiwisincebirth** [wwarthen/RomWBW#410]
Improvement in User Guide (and some related fixes) to document how to setup realtime clock in Z-System operating systems

**Comment by kiwisincebirth** [comment]
I dont have the capability to build the PDF documentation as running on OSX, this will need to bue built and committed seperately

**Comment by wwarthen** [comment]
Thank you @kiwisincebirth.  I have merged your changes and regfenerated the PDF documents.  The result has been posted as RomWBW Development Snapshot v3.5.0-dev.73.

I believe this issue is not resolved and is being closed.

Thanks! Wayne
