### ISSUE TITLE
Possible Bug in LCD.ASM

### ISSUE THREAD

**Issue by kiwisincebirth** [wwarthen/RomWBW#413]
I just reviewed your latest commit (lcd.asm), and there may be a bug where the incorrect CPU type is displayed for Z180 processors. This is due to the mis-definition of the text strings for each cpu type. 

From lcd.asm

```
LCD_CPU_Z80	.DB	"Z80",0
LCD_CPU_Z180	.DB	"Z180-K",0
LCD_CPU_Z180K	.DB	"Z180-N",0
LCD_CPU_Z180N	.DB	"Z180",0
LCD_CPU_Z280	.DB	"Z280",0
```

should be ?

```
LCD_CPU_Z80	.DB	"Z80",0
LCD_CPU_Z180	.DB	"Z180",0
LCD_CPU_Z180K	.DB	"Z180-K",0
LCD_CPU_Z180N	.DB	"Z180-N",0
LCD_CPU_Z280	.DB	"Z280",0
```

**Comment by wwarthen** [comment]
Wow @kiwisincebirth, I'm impressed you found that.  Thank you.  I'm out of town for the next 5 days, but will correct when I return.

Thanks, Wayne

**Comment by kiwisincebirth** [comment]
See PR for this issue, as noted the IDE I use strips trailing whitespace from line, hope this doesn't bother you.

**Comment by kiwisincebirth** [comment]
PR Has been merged
