### ISSUE TITLE
Doc Improvement - Userguide - Disk Management

### ISSUE THREAD

**Issue by kiwisincebirth** [wwarthen/RomWBW#417]
I am working on improvements to the User guide covering the sections on "Disk Management", and "Disk Images", etc

Why: I recently went through the processes documented in these sections, but thought to docs could be improved

So What has improved
* General reorganisation of the content into more concise sections
* Consolidation and removal of repetition of the same information
* More formalised tone of the documentation removing some to the conversational style
* A better TOC.

While the above is just about improving the documentation. I have added new content in the user guide PDF See the following sections which were mostly written from scratch
* Section 4.1 - general introduction of specific terms (specifically slice) - so that the rest of the document flows and reads well, without getting into the full details of these terms
* Section 7.2.4 - which is how I copy individual slices to my media, tested and this works.

**Comment by wwarthen** [comment]
This sounds very nice, Mark.  I will review all of this later today.

Thanks! Wayne

**Comment by wwarthen** [comment]
Hi @kiwisincebirth,

I just finished a brief review of the User Guide changes.  I really like what you have done.  The additional specifics are very helpful and I like the updated TOC flow.  Thank you very much for this contribution.

Just a couple of things I propose to address after merging your changes:

- I think the Genesis platform information got dropped.
- I would like to add a section at the beginning of disk preparation that summarizes the two different approaches to preparing disk media: manual vs. disk images.  I am a bit worried that a novice user will see the Disk Preparation section prior to the Disk Images section and not realize the manual approach is not required if you use disk images.

Are you OK if I make those two updates after merging your work?

Thanks, Wayne

**Comment by wwarthen** [comment]
On second thought, I think I will just go ahead and do the merge and add my changes.  I will leave this issue open for now in case you want to comment on my changes.

Thanks, Wayne

**Comment by kiwisincebirth** [comment]
Thanks for the comments, corrections and mention in the main readme files. And yes adding the content to start of disk preparation section makes sense. Images are clearly fundamental. After further review, can I suggest the following as well.

* Create a definition of "Disk Image" in Section 4.1 "Key Terminology Concepts", to define and introduce and promote this concept early 
* Move Section 10 "FAT Filesystem" up to section 8, so it follows on from the Disk Management sections I have just edited.

**Comment by kiwisincebirth** [comment]
PS. I may make further PR just to address some very minor issues that I come across after my large edit.

**Comment by wwarthen** [comment]
> PS. I may make further PR just to address some very minor issues that I come across after my large edit.

Sure.  Just be sure to pick up my small changes.  Thanks!

**Comment by kiwisincebirth** [comment]
I have added another PR to finalise this change. Primarily I have migrated the FAT documentation into the transferring files section, plus a few other small improvements / corrections.

https://github.com/wwarthen/RomWBW/pull/421/files

**Comment by wwarthen** [comment]
Thank you @kiwisincebirth.

I have mixed feelings about moving the FAT section inside the File Transfer section, but I realize it is primarily for file transfer.  So, I will go ahead with your changes as is.  If I get any feedback about the location of the FAT section, I may move it back.

Thanks! Wayne

**Comment by kiwisincebirth** [comment]
The primary reason for the change was that both section gave instructions guidance for the use of FAT for copying files, and as you stated the only purpose for Fat was for transferring files, that I am aware of. 

However if you want to revert, I put the Fat changes in a seperate commit, which would make it easier to revert.

Mark.

**Comment by kiwisincebirth** [comment]
And PS, regarding the build of the doc files, thanks for improving the docs for build under MacOS. I assumed the Roboto font was needed, installed and built using makefile. Comparing the resultant Pdf's against files you had built, visually they looked identical to me.

**Comment by wwarthen** [comment]
Yeah, I noticed they were pretty bad.

**Comment by wwarthen** [comment]
Thanks again for all your help with the documentation @kiwisincebirth.  I really appreciate it.

-Wayne
