### ISSUE TITLE
`TMSMODE_MSX9958` fails to build on the latest snapshot

### ISSUE THREAD

**Issue by cookingboy3** [wwarthen/RomWBW#423]
I've been running some reconfigured builds for testing [dinolab's V9958 card](https://www.tindie.com/products/dinotron/v99x8-msx-rgb-video-module-for-rc2014-v38/) and checked out the latest snapshot, but despite `TMSMODE_MSX9958` still being listed in the cfg file, it doesn't seem to be recognized during the build:
```
Enter platform [ DUO DYNO EPITX FZ80 GMZ180 HEATH MBC MK4 MON N8 NABU RCZ180 RCZ280 RCZ80 RPH S100 SBC SCZ180 UNA Z80RETRO ZETA ZETA2 ] :RCZ80
Enter config for  [ commie skz_std std substd jbl tiny_std zrc_ram_std easy_std kio_std zrc512_std zrc_std user ] :substd


Building RCZ80 substd


make[3]: Entering directory '/home/oriki/romwbw-v3.5.0/Source/HBIOS'
../../Tools/Linux/uz80as -t z80 -dBASH hbios_env.asm hbios_env.com hbios_env.lst

+ ../../Tools/Linux/uz80as -t z80 -dBASH hbios_env.asm hbios_env.com hbios_env.lst
Config/RCZ80_substd.asm:67: undefined label (TMSMODE_MSX9958)
make[3]: *** [Makefile:116: hbios_env.com] Error 1
make[3]: Leaving directory '/home/oriki/romwbw-v3.5.0/Source/HBIOS'
make[2]: *** [Makefile:21: start] Error 2
make[2]: Leaving directory '/home/oriki/romwbw-v3.5.0/Source/HBIOS'
make[1]: *** [Makefile:43: rom] Error 2
make[1]: Leaving directory '/home/oriki/romwbw-v3.5.0/Source'
make: *** [Makefile:12: source] Error 2
```

A bit of CSI seems to indicate this is due to some changes in the master `cfg_RCZ80.asm` that didn't get propagated down to the std config's comments. I haven't really gotten a chance to test it, but I'm guessing any additional functionality got moved under the `TMS80COLS` label. Basically just filing a bug to check that this is an issue with the comment and not the code and that the recommended way to run a V9958 now is to just leave `TMSMODE` set to `TMSMODE_MSX`.

Thanks!

**Comment by wwarthen** [comment]
Thank you @cookingboy3.

Yes, I'm sure you are right.  I need to update the config file comments.  I am really backlogged, but will take care of this in the next few days.

I think in your case you want TMSMODE_MSX and also to set TMS80COLS to TRUE.  I do see that TMS80COLS is missing from the config file and I will be adding that as well.

Thank you for bringing this to my attention.

-Wayne

**Comment by wwarthen** [comment]
I have posted RomWBW Development Snapshot v3.5.0-dev.81.  I went through a full cleanup cycle on all the config files and I believe that this issue is resolved.  I am going to close this issue, but feel free to reopen it if there are any problems.

Thanks! Wayne
