### ISSUE TITLE
Syntax error when building

### ISSUE THREAD

**Issue by wdl1908** [wwarthen/RomWBW#435]
https://github.com/wwarthen/RomWBW/blob/6005472fa7c6867997f2199736b2d0c9cd79b55b/Source/HBIOS/hbios.asm#L5246

This and the following line are missing semi colons

**Comment by wwarthen** [comment]
Thank you @wdl1908.

I just checked-in the fix for this.

-Wayne

**Comment by kiwisincebirth** [comment]
thanks @wwarthen - That was my fault

**Comment by wwarthen** [comment]
I am pretty sure this is resolved, so I am going to close the issue.  Please let me know if there are any related problems.

Thanks, Wayne
