### ISSUE TITLE
Z3Plus CPM Distribution Disk Image

### ISSUE THREAD

**Issue by kiwisincebirth** [wwarthen/RomWBW#446]
I have installed a Z3Plus and learning about it, while it has its pros and cons it is well documented, thus i think it would make a worthy disk image, I was considering contributing it as a disk image thus the interest in files, etc.  

The complexity (for me) comes from the fact that the NZ-COM and Z3PLUS distribution(s) were literally zipped at the same time, and the contents ARE largely identical, so would have to ensure mostly reuse of the work done on NZ-COM. 

Questions
* the readme file ( in images/d_nzcom ) folder, is this a complete list of how you customised NZ-COM ? 
* Any suggestions ?

i.e from the original distrubutions

```
% diff -b nzcom z3plus
Binary files nzcom/!(C)1988 and z3plus/!(C)1988 differ
Only in nzcom: !NZ-COM
Only in z3plus: !VERS--1.02F
Only in nzcom: !VERS--1.2H
Only in z3plus: !Z3PLUS
Binary files nzcom/ALIAS.CMD and z3plus/ALIAS.CMD differ
Only in nzcom: BGZRDS19.LBR
Only in nzcom: HELP.COM
Only in nzcom: MKZCM.COM
Only in nzcom: NZ-DBASE.INF
Only in nzcom: NZBLITZ.COM
Only in nzcom: NZBLTZ14.CFG
Only in nzcom: NZBLTZ14.HZP
Only in nzcom: NZCOM.COM
Only in nzcom: NZCOM.LBR
Only in nzcom: NZCPR.LBR
Only in z3plus: PATCH4SK.HEX
Only in z3plus: PATCHSK.SUB
Only in nzcom: PUBLIC.COM
Binary files nzcom/RELEASE.NOT and z3plus/RELEASE.NOT differ
Only in nzcom: SHOW.COM
Only in nzcom: SUB.COM
Only in nzcom: Z3LOC.COM
Only in z3plus: Z3PLUS.COM
Only in z3plus: Z3PLUS.LBR
Only in z3plus: ZHELP.COM
Only in z3plus: ZSHOW.COM
```

**Comment by wwarthen** [comment]
Excellent.  I had always wanted to include a Z3Plus disk image.  Just hadn't gotten to it.

>The complexity (for me) comes from the fact that the NZ-COM and Z3PLUS distribution(s) were literally zipped at the same time, and the contents ARE largely identical, so would have to ensure mostly reuse of the work done on NZ-COM.

Yes, I understand the conundrum.  I agree it is preferable to avoid duplicate files.  One approach would be to "pick" the common files out of the NZCOM disk source in the Z3Plus creation script.  However, this will result in a lot of individual files/lines -- not very maintainable.  The alternative is to create a new folder under Source/Images/Common for these shared NZCOM/Z3Plus files.  I'm not sure what to call such a folder.  I guess I am OK with either approach at this point.

>the readme file ( in images/d_nzcom ) folder, is this a complete list of how you customised NZ-COM ?

Yes, I am pretty sure it is complete.

Thanks, Wayne

**Comment by kiwisincebirth** [comment]
> The alternative is to create a new folder under Source/Images/Common for these shared NZCOM/Z3Plus files. I'm not sure what to call such a folder. I guess I am OK with either approach at this point.

I have called the folder "PluPerfect" - but again its arbitrary.

Question:

There are TWO (binary identical) files in NZCOM with conflicting names to CPM/3 and in this scenario, they have been renamed in Z3PLUS, (typically Z prefix) to avoid CPM3 name conflict. e.g.
* nzcom name -> z3plus name
* SHOW.COM -> ZSHOW.COM
* HELP.COM -> ZHELP.COM

I also found ZSHOW and ZHELP in ZPM3 Distro, so clearly the Z prefix is consistent. I guess is there any advantage in NZCOM to rename these file (which can now be shared). So either
  (a) - Generally rename SHOW to ZSHOW (in NZCOM) and have a single shared file
        user of existing OS's will have to convert to the new name, or not if an ALAIS is created(?)
  (b) - maintain seperate copies of the file (different names) in each disk
        users will have to remember the name difference when switching OS's

**Comment by wwarthen** [comment]
Hi @kiwisincebirth 

> Question:
> 
> There are TWO (binary identical) files in NZCOM with conflicting names to CPM/3 and in this scenario, they have been renamed in Z3PLUS, (typically Z prefix) to avoid CPM3 name conflict. e.g.
> 
> * nzcom name -> z3plus name
> * SHOW.COM -> ZSHOW.COM
> * HELP.COM -> ZHELP.COM
> 
> I also found ZSHOW and ZHELP in ZPM3 Distro, so clearly the Z prefix is consistent. I guess is there any advantage in NZCOM to rename these file (which can now be shared). So either (a) - Generally rename SHOW to ZSHOW (in NZCOM) and have a single shared file user of existing OS's will have to convert to the new name, or not if an ALAIS is created(?) (b) - maintain seperate copies of the file (different names) in each disk users will have to remember the name difference when switching OS's

I suggest using ZSHOW and ZHELP consistently.  Just make sure to update the ZSDOS notes to reflect that this was done.

Thanks, Wayne

**Comment by kiwisincebirth** [comment]
Its alive, but Its not small.

```
P15>diskinfo a:
Free data space             4956 Kb of 8144 Kb total (8176 Kb disk)
Number of files             275 using 3188 Kb.  Average 11 Kb

P15>z3loc
System  Elements   Base  Addresses
----------------   ---------------
    CCP            D700h (ZCPR 3.4)      (20 recs)
    BDOS           F006h (CP/M 3.1)      (12 recs)
    BIOS           F600h (HD64180/Z180)
    RSX (lowest)   D306h
```

**Comment by wwarthen** [comment]
Seems to be working very well for me.

Thanks @kiwisincebirth

**Comment by kiwisincebirth** [comment]
Seems to work, for me. Most of the work was Mving all the NZ com files into a Common directory. and updating the startfiles to correctly load the default's (Path, TCap, and NDR) at startup. 

The biggest issue is the floppy disk, I had to really cut it back, definitely stuff missing (commented in the FD_.txt file). There is not an easy solution, except go through and work out what shouldn't be on every OS disk image. e.g. 

* 4 x copies of basic, 
* N copies of terminal applications
* N copies of File transfer app, maybe we need one.
* Needles documentation, that could could be in /Doc directory.
* DDTZ - debugging tool

...and then where to place it ? Maybe an "Everything Else" disk for all the minor stuff, we do have 16 user areas after all, but again space of 144mb could be a problem. 

Currently there are a number of very specific disk images, some with just a few files. Why not consider having a Disk for a category of application (eg. Basic). You could put all Basic languages on a single disk, (seperate User area's). But also you could have a disk for MicroSoft programming languages. incl Basic, Fortran Cobol, etc;  A disk for C compilers, etc. At this point it becomes personal preference, as how you organise.

Just idea's for thought.

**Comment by wwarthen** [comment]
Yes, the floppy disk space issue is a little annoying.

Many years ago when the disk image process was created, there was basically no problem including the same contents on the floppy as the hard disk images.  Over time, it has become more and more challenging as content has increased.

I agree that it is probably best to significantly simplify the add-on files on the floppy disk images.  However, I don't want the image generation scripts to get much more complicated.  I will take a look at this over the next few days.  Your idea of a supplemental floppy disk image that has a bunch of the add-on applications might be a good idea.

Honestly, I'm not sure how much effort should go into the floppy disk images.  They are rarely used.

Yes, there are many disk images with just a few files.  Many of these were contributed.  At the time, I suggested consolidating these by utilizing user areas.  However, the user community seemed to be strongly in favor of individual disk images.

Thanks, Wayne

**Comment by wwarthen** [comment]
Hi @kiwisincebirth,

I wonder if we can close this issue?  I realize your comments about the floppy content situation have not been addressed, but that seems like it would be better in a new thread if desired.

Thanks, Wayne

**Comment by wwarthen** [comment]
I think we can consider this issue complete.

Thank you @kiwisincebirth!
