### ISSUE TITLE
M80 on Microsoft Basic (compiled) disk does not work.

### ISSUE THREAD

**Issue by huntrods** [wwarthen/RomWBW#462]
Confirmed by Wayne on the google groups 2024-12-07, the version of M80 that is on the disk image containing the Microsoft Basic compiler (BASCOM.COM, BASCOM.HLP, BASCOM2.HLP, BASLIB.REL ... L80.com ... M80.COM, MBASIC.COM, ...) does not work. If you try to assemble a program using the standard command, i.e. "M80 =MYPROG.ASM", it returns to the drive prompt immediately and thereafter the RC2014 is unresponsive. You have to reboot the machine before it works.

**Comment by wwarthen** [comment]
I have updated M80 in the bascomp disk image from v3.43 to v3.44.  The newer version seems to work fine.  I have no idea what was wrong with v3.43.

I am closing this issue since I am pretty confident it is resolved with the associated check-in.

Thanks, Wayne
