### ISSUE TITLE
netboot.mod spelling

### ISSUE THREAD

**Issue by b1ackmai1er** [wwarthen/RomWBW#463]
Duodyne [DUO_cust] Boot Loader
AutoBoot:
Boot [H=Help]: n
Loading Network Boot...
MT011 WizNET Network Boot
No NVRAM confiuration
Network boot error

"confiuration" in netboot.mod

I believe the original source file for this is https://github.com/durgadas311/cpnet-z80/blob/master/src/cpnboot.asm and has the correction but cannot find the the Romwbw implementation.

Regards Phil.

**Comment by wwarthen** [comment]
Thank you @b1ackmai1er.  I should be able to track this down and fix it.

-Wayne

**Comment by wwarthen** [comment]
Hi @b1ackmai1er,

Well, it took some digging, but I finally found the old email thread with Douglas Miller regarding `netboot.mod`.  Unfortunately, it is not derived from `cpnboot.asm`.  From the old thread, Douglas indicated that it was complicated to build the module and therefore not included in the [cpnet-z80 repository](https://github.com/durgadas311/cpnet-z80).

In addition to the typo, the existing `netboot.mod` is hardwired to work with the MT011 RCBus Module.  It would be good if there were a variant of if for the Duodyne.

I will contact Douglas and see if there is an easy way to address this.

Thanks, Wayne

**Comment by durgadas311** [comment]
I will take a look at this and dust off those old memory cells. What's the I/O address(es) for the duodyne version?

**Comment by durgadas311** [comment]
@wwarthen I may need some help remembering how a *.mod file differs from other executable images. I should have make rules to build it somewhere, but will need to track that down. I think at the time I originally created this it was not yet formalized, but since have integrated it better into some repository.

**Comment by wwarthen** [comment]
Thanks @durgadas311.

I don't think there is any rush on this.

The SPI I/O port on the DUO is at 0x8C.  You can refer to https://github.com/durgadas311/cpnet-z80/blob/master/src/duo/config.lib.

The .mod file is loaded at 0x0100.  That is also the code entry point.  I have 4K allocated for the binary which I think was more than needed.  You may have sent me a larger binary previously, but it was mostly null padded and I chopped it down to 4K.

Thanks! Wayne

**Comment by durgadas311** [comment]
Thanks! I had forgotten that you added the duo to cpnet-z80. I'll try to find where I built netboot.mod. Worst case I can disassemble it and it should all come back to me.

**Comment by durgadas311** [comment]
I located the repository where I was building netboot.mod, and fixed the spelling error.

https://github.com/durgadas311/minimalCPM/tree/master/rom

Unfortunately, this project duplicated some code  from cpnet-z80, so it's not ideal. It started out as experimentation on what was a minimal system configuration that could run CP/M, but then was a convenient place to also build RomWBW netboot.mod. Anyway, I'll probably just add Duodyne support there, and leave fixing my atrocities against software engineering for another day.

**Comment by wwarthen** [comment]
FYI, am currently dead in the water with a power outage at home.  May be another 2-3 days.

**Comment by durgadas311** [comment]
As I start to look into what this will take, I may need more info on the DUO WizNET board. Does it include an NVRAM chip? I also see that my current build was creating an 8K file for netboot.mod - so should that be changed? what was the affect of it being 8K?

**Comment by durgadas311** [comment]
I think I found the schematic, https://github.com/lynchaj/duodyne/blob/main/08%20input-output.Disk%2C%20V1.0/input-output.Disk.schematic.pdf, which indicates Wiz850io, 25LCxxx NVRAM, and an SD-Card socket.

So, if that's up-to-date, I just need to hear whether I should pad the binary netboot.mod files to 4K or 8K.

**Comment by wwarthen** [comment]
@durgadas311

Yes, the DUO WizNet board does include an 25LC512 NVRAM chip.  It works OK with WIZCFG.

Yes, you originally provided me with an 8K image.  I saw that it did not use most of this space and simply truncated it to 4K to save space in the RomWBW ROM.  You can provide an 8K image or a 4K image -- whatever it easy for you.

Just saw your latest post.  Yes, that is the right schematic.  Padding to 4K would be idea.

Thanks, Wayne

**Comment by durgadas311** [comment]
OK, here's something to try:

http://sebhc.durgadas.com/netboot-wbw-wiz.mod is the MT011 version of netboot.mod

http://sebhc.durgadas.com/netboot-wbw-wzd.mod is the DuoDyne version.

I've compared the MT011 version with the original and the differences all seem to be expected (some addresses shifted by one byte after the spelling correction added one byte).

**Comment by wwarthen** [comment]
Thanks!

I'm afraid it may take me until Sunday to get to this.  For some of the testing, I need reconfigure some hardware and I have commitments tomorrow.  Anyway, I will let you know as soon as possible.

Thanks, Wayne

**Comment by durgadas311** [comment]
I've organized the CP/NET files for RomWBW MT011 and DuoDyne systems into separate directories:

http://sebhc.durgadas.com/romwbw-duo/

http://sebhc.durgadas.com/romwbw-mt011/

This includes a build of CP/NOS for each, although not sure if anyone is using those (CP/NOS has no local disks). Since netboot.mod is meant to run from the ROM before CP/M is started, I'm thinking they typical image to boot was CP/NOS. But, it's been a few years and I was doing a lot of different CP/NET configurations back then.

**Comment by wwarthen** [comment]
I completed the integration and testing of the netboot modules.  Everything is working perfectly.  Thanks @durgadas311!

I just need to update some RomWBW documentation and then I will commit the udpates.

Thanks, Wayne

**Comment by wwarthen** [comment]
OK, updates are committed and everything seems to check out.

I am going to go ahead and close this issue since I believe it is fully resolved.

Thanks, Wayne
