### ISSUE TITLE
Monsputer platform deprecated

### ISSUE THREAD

**Issue by jpelletier** [wwarthen/RomWBW#483]
Code specific for this platform can be removed since it's only one computer made and it currently runs only CP/M 2.2. 
If I make another Z80 computer, it will follow common standards already used for RomWBW.

**Comment by wwarthen** [comment]
Thank you for letting me know @jpelletier.

I make the changes in the next few days.

Thanks, Wayne

**Comment by wwarthen** [comment]
Completed in commit 751cc62.
