### ISSUE TITLE
hbios - PPIDE file copy

### ISSUE THREAD

**Issue by feilipu** [wwarthen/RomWBW#63]
I'm using ChaN FAT file system, with a diskio driver to HBIOS. Using the relevant calls for the SD card interface I can successfully copy a file. Using the PPIDE (82C55) interface the SC130 system reboots during copying.

Not sure what is happening, but the monitor copy is attached below for reference.

I've attached a copy of the C code in [fileCopyTest.c](https://github.com/wwarthen/RomWBW/files/4015765/fileCopyTest.c.txt).

The functions calling HBIOS are `f_read()` and `f_write()`. These functions are [implemented here](https://github.com/feilipu/z88dk-libraries/blob/master/diskio_hbios/source/diskio_hbios.c), calling HBIOS functions via [C wrappers in z88dk](https://github.com/z88dk/z88dk/tree/master/libsrc/_DEVELOPMENT/arch/hbios).

As noted, the code works perfectly for the HBIOS SD interface, and also works substantially correctly for the PPIDE interface, as sufficient correctness is present to successfully mount the drive, read directories, and open and create files. It seems only to fail when doing the actual copy process.

Wondering if you've any hints?
Or thoughts about where to look?

Phillip

```sh
RetroBrew HBIOS v2.9.2-pre.22, 2019-11-30

SC130 Z8S180-N @ 36.864MHz IO=0xC0
1 MEM W/S, 2 I/O W/S, INT MODE 2
512KB ROM, 512KB RAM

ASCI0: IO=0xC0 ASCI W/BRG MODE=115200,8,N,1
ASCI1: IO=0xC1 ASCI W/BRG MODE=115200,8,N,1
DSRTC: MODE=STD IO=0x0C NOT PRESENT
MD: UNITS=2 ROMDISK=384KB RAMDISK=384KB
PPIDE: IO=0x20 DEVICES=2
PPIDE0: LBA BLOCKS=0x0767D000 SIZE=60666MB
PPIDE1: NO MEDIA
SD: MODE=SC OPR=0x0C CNTR=0xCA TRDR=0xCB DEVICES=1
SD0: SDHC NAME=NCard BLOCKS=0x00779800 SIZE=3827MB

Unit        Device      Type              Capacity/Mode
----------  ----------  ----------------  --------------------
Char 0      ASCI0:      RS-232            115200,8,N,1
Char 1      ASCI1:      RS-232            115200,8,N,1
Disk 0      MD1:        RAM Disk          384KB,LBA
Disk 1      MD0:        ROM Disk          384KB,LBA
Disk 2      PPIDE0:     Hard Disk         60666MB,LBA
Disk 3      PPIDE1:     Hard Disk         --
Disk 4      SD0:        SD Card           3827MB,LBA


SC130 Boot Loader

ROM: (M)onitor (C)P/M (Z)-System (F)orth (B)ASIC (T)-BASIC  
Disk: (0)MD1 (1)MD0 (2)PPIDE0 (3)PPIDE1 (4)SD0 

Boot Selection? M

Loading Monitor...


Monitor Ready (H for Help)
>L

Loaded
>R100

FatFs.fs_type 3
FatFs.fsize 7640

Opening 4:random1.txt - Opened
Creating 4:random2.txt - Created

Copying...
Copied 1048576 bytes, the time taken was 44.8000 seconds

Monitor Ready (H for Help)
>L

Loaded
>R100

FatFs.fs_type 3
FatFs.fsize 15161

Opening 2:random1.txt - Opened
Creating 2:random2.txt - Created

Copying...

RetroBrew HBIOS v2.9.2-pre.22, 2019-11-30

SC130 Z8S180-N @ 36.864MHz IO=0xC0
1 MEM W/S, 2 I/O W/S, INT MODE 2
512KB ROM, 512KB RAM

ASCI0: IO=0xC0 ASCI W/BRG MODE=115200,8,N,1
ASCI1: IO=0xC1 ASCI W/BRG MODE=115200,8,N,1
DSRTC: MODE=STD IO=0x0C NOT PRESENT
MD: UNITS=2 ROMDISK=384KB RAMDISK=384KB
PPIDE: IO=0x20 DEVICES=2
PPIDE0: LBA BLOCKS=0x0767D000 SIZE=60666MB
PPIDE1: NO MEDIA
SD: MODE=SC OPR=0x0C CNTR=0xCA TRDR=0xCB DEVICES=1
SD0: SDHC NAME=NCard BLOCKS=0x00779800 SIZE=3827MB

Unit        Device      Type              Capacity/Mode
----------  ----------  ----------------  --------------------
Char 0      ASCI0:      RS-232            115200,8,N,1
Char 1      ASCI1:      RS-232            115200,8,N,1
Disk 0      MD1:        RAM Disk          384KB,LBA
Disk 1      MD0:        ROM Disk          384KB,LBA
Disk 2      PPIDE0:     Hard Disk         60666MB,LBA
Disk 3      PPIDE1:     Hard Disk         --
Disk 4      SD0:        SD Card           3827MB,LBA

SC130 Boot Loader

ROM: (M)onitor (C)P/M (Z)-System (F)orth (B)ASIC (T)-BASIC  
Disk: (0)MD1 (1)MD0 (2)PPIDE0 (3)PPIDE1 (4)SD0 

Boot Selection? M

Loading Monitor...

Monitor Ready (H for Help)
>
```

**Comment by wwarthen** [comment]
Surprising.  Nothing occurs to me right off.  It is certainly possible there was a regression in my code.  I will do some regression testing today.

-Wayne

**Comment by wwarthen** [comment]
I tried to recreate this issue using my SC126 and a PPIDE adapter.  I used my FAT application under CP/M for testing just because I could do it quickly.  The FAT application is based on FatFS.  I had no problem repeatedly copying files to/from the FAT filesystem.  Also no problem just copying from and to the FAT filesystem in a single operation.  I did this with a 1MB file and tried repeatedly with no issues.

In the end, this doesn't mean too much because there are so many edge cases that are hard to take into account.

- When your system restarts during a copy operation, does it do so near the start, middle, or end of the copy process?

-  I don't see anything strange in your code.  It is substantially similar to the functions I use in the FAT application.

- I note that you are using a much larger CF Card than I am.  Not sure why that would matter though.

- You are running under the debug monitor and I am running under CP/M.  However, there are literally no CP/M calls involved when FAT.COM copies a file to & from the FAT partition.

I will think about this some more.  Not immediately sure what to try next.

-Wayne

**Comment by feilipu** [comment]
Thanks for checking, Wayne.

I'll have to try breaking it down further to get a result.
Try some repeated reads, and repeated writes, perhaps.

I tried using the RC2014 last night too, with the same `+hbios` target code. The result is similar, but there is no reboot. Instead it creates the file (with 0 bytes), and returns to dbgmon instead of copying.

The only "dog-walk thought" that I occured was there was something odd in my timer functions. They are being called directly before the copy action, so this would result in a similar symptom.

**Comment by wwarthen** [comment]
It occurred to me that I should try the FatFS I/O test module on a PPIDE device.  I did this and it passed all tests repeatedly.  I am still stumped.  I hope you can find something.

-Wayne

**Comment by feilipu** [comment]
I've done a little more back to back testing, and seen the following.
The reset issue has gone away. Must have been doing something stupid, but the copy program is not working.
My simple mount-open-write-read test program works perfectly fine.
Sometimes, the copy loop errors out on the write, leaving one buffer full of data correctly written.
Mostly, the copy loop errors out on the first read, leaving 0 bytes copied.

Every time, the error is the same [INVAILID_OBJECT](https://github.com/feilipu/z88dk-libraries/blob/master/ff/source/ff.h#L291). This error is generated (potentially) by the [`validate()`](https://github.com/feilipu/z88dk-libraries/blob/master/ff/source/ff.c#L3671) function, if the drive is not properly initialised (correct is return 0).

I am concerned that simply calling [`BF_DIOSTATUS`](https://github.com/feilipu/z88dk-libraries/blob/master/diskio_hbios/source/diskio_hbios.c#L76) may not be giving the expected 0 answer, if the drive is busy?

Otherwise, further work on this tonight.

**Comment by wwarthen** [comment]
In theory, the only way that DIOSTATUS will return a non-zero result is if a prior I/O request failed.  However, if that happened, you would have gotten an error from the I/O call itself.  Sorry I don't have any ideas.

-Wayne

**Comment by feilipu** [comment]
OK. Kind of a learning experience.
The issue was nothing at all to do with what I suspected.

[`f_mount()`](http://elm-chan.org/fsw/ff/doc/mount.html) requires a pointer to a FATFS filesystem object.
Feeding it the address of a filesystem object is not sufficient.
That is one degree of abstraction too few, and boom, the filesystem object is invalid, so we get the error above.

Explains why my simple program worked properly (because it used `malloc()` to allocate a FATFS filesystem object) but my copy program didn't do this (it just provided the address of a bss allocated filesystem object), and so it failed.

Sorry for being think.

**Comment by wwarthen** [comment]
Ah, that does explain it.  Glad you got it resolved!  Kind of surprised it was only affecting things when the PPIDE driver was being used, but I have seen stranger things.

**Comment by feilipu** [comment]
The issue started just with PPIDE, but actually I could get it to affect everything during testing.

SDCC is quite unpredictable where it puts stuff on the stack. Even changing the optimisation pressure can have a major effect on how the stack is managed. So initially I was getting reboots only with PPIDE, then failures just with PPIDE, then failures (depending on unknown stuff) everywhere.

I guess it just depended whether the specific stack position at the pointer address was being clobbered by another thing. The SD driver would certainly be using the stack differently, and that may have been the cause of the differing symptoms. But, I can't really tell.
