### ISSUE TITLE
profile.sub requires submit.com

### ISSUE THREAD

**Issue by b1ackmai1er** [wwarthen/RomWBW#75]
HI Wayne,
I installed the fd_nzcom.img on my gotek floppy drive emulator and was pleased to see this boots from the main menu. I created my ZCPR profile (PMS) and setup NZCOM to startup automatically with my profile by adding NZCOM PMS the profile.sub file. However this fails to boot because SUBMIT.COM is not part of the image. Suggest adding submit.com to all images or change cbios to always look on B: for submit.com at boot. Or you may be happy with this being the way it is, with user installing if using the facility. Regards Phil

**Comment by wwarthen** [comment]
Yes, SUBMIT.COM should be added to that image.  I will take care of it soon.

-Wayne

**Comment by wwarthen** [comment]
I have added SUMBIT.COM to the NZCOM disk image fileset.  It looks like all of the other disk image filesets already had it (except for WordStar which is not a bootable image).
