### ISSUE TITLE
Linux build issue

### ISSUE THREAD

**Issue by b1ackmai1er** [wwarthen/RomWBW#83]
Hi Curt, Wayne,

I set up a linux box and am trying out your new build script. 

First thing i notice is that  "copying directory d_bp/u15" is very slow compared to other copies to the image. I know this is copying a lot of files compared to other images but u14 proceeds quickly then speed slows right down from start of u15 copy.

I do get an error:

/bin/sh: 1: cd: can't cd to /home/phillip/github/RomWBW/../RomWBW.windows

which appears to be coming from Tools/Makefile.inc

and the make process does not get to the HBIOS build process.

If I go to the HBIOS directory and start make I get the same error and the process does not complete.

Not sure if I'm doing something wrong (long time since I used linux) or this is a bug.

Also comes up in make clean.

This is the last output from make:

cat hd_cpm22.img hd_zsdos.img hd_nzcom.img hd_cpm3.img hd_zpm3.img hd_ws4.img hd_bp.img > hd_combo.img
copy fd_cpm22.img to ../../Binary
copy fd_zsdos.img to ../../Binary
copy fd_nzcom.img to ../../Binary
copy fd_cpm3.img to ../../Binary
copy fd_zpm3.img to ../../Binary
copy fd_ws4.img to ../../Binary
copy hd_cpm22.img to ../../Binary
copy hd_zsdos.img to ../../Binary
copy hd_nzcom.img to ../../Binary
copy hd_cpm3.img to ../../Binary
copy hd_zpm3.img to ../../Binary
copy hd_ws4.img to ../../Binary
copy hd_bp.img to ../../Binary
copy hd_combo.img to ../../Binary
make[2]: Leaving directory '/home/phillip/github/RomWBW/Source/Images'
make[1]: Leaving directory '/home/phillip/github/RomWBW/Source'
cd Source/Images ; make
make[1]: Entering directory '/home/phillip/github/RomWBW/Source/Images'
/bin/sh: 1: cd: can't cd to /home/phillip/github/RomWBW/../RomWBW.windows
copy fd_cpm22.img to ../../Binary
copy fd_zsdos.img to ../../Binary
copy fd_nzcom.img to ../../Binary
copy fd_cpm3.img to ../../Binary
copy fd_zpm3.img to ../../Binary
copy fd_ws4.img to ../../Binary
copy hd_cpm22.img to ../../Binary
copy hd_zsdos.img to ../../Binary
copy hd_nzcom.img to ../../Binary
copy hd_cpm3.img to ../../Binary
copy hd_zpm3.img to ../../Binary
copy hd_ws4.img to ../../Binary
copy hd_bp.img to ../../Binary
copy hd_combo.img to ../../Binary
make[1]: Leaving directory '/home/phillip/github/RomWBW/Source/Images'

phillip@phillip-GA-990FXA-UD3:~/github/RomWBW$ cd Source/
phillip@phillip-GA-990FXA-UD3:~/github/RomWBW/Source$ cd HBIOS/
phillip@phillip-GA-990FXA-UD3:~/github/RomWBW/Source/HBIOS$ make
/bin/sh: 1: cd: can't cd to /home/phillip/github/RomWBW/../RomWBW.windows
copy ZETA2_std.rom to ../../Binary
phillip@phillip-GA-990FXA-UD3:~/github/RomWBW/Source/HBIOS$

**Comment by b1ackmai1er** [comment]
Creating the /github/ROMWBW.windows directory eliminates the cd error.

I see now that the build process is just hardcoded for ZETA2. The rom file that is generated is not 512K.

I changed build for SBC and got a similar result with a couple of issues

phillip@phillip-GA-990FXA-UD3:~/github/RomWBW/Source/HBIOS$ make
bash Build.sh SBC std 512
```
Building for SBC_std for SBC std 512
creating empty rom disk of size 512 in Blank512.dat
384+0 records in
384+0 records out
393216 bytes (393 kB, 384 KiB) copied, 0.00286092 s, 137 MB/s
cp: cannot stat '../Fonts/font*.asm': No such file or directory
make[1]: Entering directory '/home/phillip/github/RomWBW/Source/HBIOS'
make[1]: 'dbgmon.bin' is up to date.
make[1]: 'prefix.bin' is up to date.
make[1]: 'romldr.bin' is up to date.
make[1]: 'eastaegg.bin' is up to date.
make[1]: 'nascom.bin' is up to date.
make[1]: 'tastybasic.bin' is up to date.
make[1]: 'game.bin' is up to date.
make[1]: 'usrrom.bin' is up to date.
make[1]: 'imgpad.bin' is up to date.
make[1]: 'imgpad0.bin' is up to date.
make[1]: Leaving directory '/home/phillip/github/RomWBW/Source/HBIOS'
make[1]: Entering directory '/home/phillip/github/RomWBW/Source/HBIOS'
make[1]: 'hbios_rom.bin' is up to date.
make[1]: 'hbios_app.bin' is up to date.
make[1]: 'hbios_img.bin' is up to date.
make[1]: Leaving directory '/home/phillip/github/RomWBW/Source/HBIOS'
Building SBC_std output files...
cat: ../CPM22/cpm_wbw.bin: No such file or directory
cat: ../ZSDOS/zsys_wbw.bin: No such file or directory
Building 512KB SBC_std ROM disk data file...
placing files into RomDisk.tmp
  ../RomDsk/ROM_512KB/ASM.COM
  ../RomDsk/ROM_512KB/CLRDIR.COM
  ../RomDsk/ROM_512KB/COMPARE.COM
  ../RomDsk/ROM_512KB/COPY.CFG
  ../RomDsk/ROM_512KB/COPY.COM
  ../RomDsk/ROM_512KB/DDT.COM
  ../RomDsk/ROM_512KB/DDTZ.COM
  ../RomDsk/ROM_512KB/DUMP.COM
  ../RomDsk/ROM_512KB/ED.COM
  ../RomDsk/ROM_512KB/FA16.CFG
  ../RomDsk/ROM_512KB/FDISK80.COM
  ../RomDsk/ROM_512KB/FILEATTR.COM
  ../RomDsk/ROM_512KB/FILEDATE.CFG
  ../RomDsk/ROM_512KB/FILEDATE.COM
  ../RomDsk/ROM_512KB/FLASH.COM
  ../RomDsk/ROM_512KB/INITDIR.CFG
  ../RomDsk/ROM_512KB/INITDIR.COM
  ../RomDsk/ROM_512KB/LDDS.COM
  ../RomDsk/ROM_512KB/LDP2D.COM
  ../RomDsk/ROM_512KB/LINK.COM
  ../RomDsk/ROM_512KB/LOAD.COM
  ../RomDsk/ROM_512KB/MBASIC.COM
  ../RomDsk/ROM_512KB/NULU.COM
  ../RomDsk/ROM_512KB/PIP.COM
  ../RomDsk/ROM_512KB/PUTDS.COM
  ../RomDsk/ROM_512KB/RELOG.COM
  ../RomDsk/ROM_512KB/RMAC.COM
  ../RomDsk/ROM_512KB/STAT.COM
  ../RomDsk/ROM_512KB/SUBMIT.COM
  ../RomDsk/ROM_512KB/SUPERSUB.COM
  ../RomDsk/ROM_512KB/TD.CFG
  ../RomDsk/ROM_512KB/TD.COM
  ../RomDsk/ROM_512KB/UNARC.COM
  ../RomDsk/ROM_512KB/XSUB.COM
  ../RomDsk/ROM_512KB/ZAP.COM
  ../RomDsk/ROM_512KB/ZCAL.COM
  ../RomDsk/ROM_512KB/ZCNFG.COM
  ../RomDsk/ROM_512KB/ZCNFG24.CFG
  ../RomDsk/ROM_512KB/ZDE.COM
  ../RomDsk/ROM_512KB/ZPATH.COM
  ../RomDsk/ROM_512KB/ZSCONFIG.COM
  ../RomDsk/ROM_512KB/ZXD.CFG
  ../RomDsk/ROM_512KB/ZXD.COM
adding apps to RomDisk.tmp
  ../../Binary/Apps/Assign.com
  ../../Binary/Apps/FDU.COM
  ../../Binary/Apps/Format.com
  ../../Binary/Apps/Mode.com
  ../../Binary/Apps/OSLdr.com
  ../../Binary/Apps/RTC.com
  ../../Binary/Apps/Survey.com
  ../../Binary/Apps/SysCopy.com
  ../../Binary/Apps/SysGen.com
  ../../Binary/Apps/Talk.com
  ../../Binary/Apps/Timer.com
  ../../Binary/Apps/xm.com
  ../../Binary/Apps/IntTest.com
copying systems to RomDisk.tmp
copy SBC_std.rom to ../../Binary
phillip@phillip-GA-990FXA-UD3:~/github/RomWBW/Source/HBIOS$ ls -las ~/github/RomWBW/Binary/SBC_std.rom 
464 -rw-r--r-- 1 phillip phillip 475136 Feb 22 12:15 /home/phillip/github/RomWBW/Binary/SBC_std.rom
phillip@phillip-GA-990FXA-UD3:~/github/RomWBW/Source/HBIOS
```$ 

Will keep playing and see if i can identify or resolve any of these issues.

Regards Phil.

**Comment by cm68** [comment]
The slowness of the copy is an n^2 algorithm that I am using to normalize filenames.  It is proportional to the size of the directory.  It's easy to fix by caching the filename mapping intermediate file.  I'll code that up soon.

**Comment by cm68** [comment]
Secondly, the HBIOS make should call the cpm22 and msdos make.

**Comment by b1ackmai1er** [comment]
Thanks Curt. As Wayne has suggested I have cancelled the changes I sent through. Happy to close this if you would prefer.

**Comment by cm68** [comment]
thanks, I am using it to track the issues you so kindly raised.  I just added the cache I referred to,
so the slowness of the copy is history.  the next pull request is coming tonight, and addresses all the issues you raised, and also has a good os-x build too.

**Comment by cm68** [comment]
at this point, the bugs you mentioned are all fixed.  I get bit-identical builds on linux and windows for the rom files, and the disk images only differ in the directory order, since the windows build for some reason ignores the diskdefs os type of 2.2 and always uses cp/m 3.

**Comment by wwarthen** [comment]
@b1ackmai1er Phil, are you OK if I close this issue?  I think all has been addressed.

Thanks, Wayne

**Comment by wwarthen** [comment]
I am going to go ahead and close this.  I believe it has been fully addressed.

Thanks, Wayne

**Comment by b1ackmai1er** [comment]
Arghhh thanks. Sorry forgot to reply.

**Comment by wwarthen** [comment]
No worries.  Thanks Phil.
