### ISSUE TITLE
Linux Build using Github Actions

### ISSUE THREAD

**Issue by electrified** [wwarthen/RomWBW#89]
As an experiment I forked the repo, and set up a Github Action to do a build, using the default Ubuntu container it suggests. It almost works! We could have a CI pipeline to automatically generate the release zips!

See here for the run: https://github.com/electrified/RomWBW/runs/473668770?check_suite_focus=true

It gets images phase and then it can't find `mkfs.cpm` it seems like `$(BINDIR)` is Linux when the tools are in `Unix`?

Also ZMAC's spinning baton generates 1000s of lines of output, so if we could somehow find a way to disable that....

Thanks for your work on this Curt and Wayne, this is awesome :)

```
make[2]: Entering directory '/home/runner/work/RomWBW/RomWBW/Source/Images'
Making Blank Floppy of size 1440k
tr: write error: Broken pipe
tr: write error
Making Blank Hd of size 8320k
tr: write error: Broken pipe
tr: write error
Generating fd_cpm22.img
copying system ../CPM22/cpm_wbw.sys to fd_cpm22.img
/bin/sh: 17: ../../Tools/Linux/mkfs.cpm: not found
```

**Comment by wwarthen** [comment]
Well, this is interesting indeed.  I would not mind having a CI pipeline.

Will see what Curt thinks...

**Comment by electrified** [comment]
Happy to help. I will try and investigate the build failure. It's using the Ubuntu latest Docker container, so should theoretically behave exactly the same as on a clean Ubuntu install.

Realised you possibly can't see the build log as it's my repo - attached is the log output

[build_output.txt](https://github.com/wwarthen/RomWBW/files/4266167/build_output.txt)

**Comment by electrified** [comment]
I figured out it was because the ncurses headers weren't installed.

Here's a PR that builds RomWBW on every pull and generates a zip:

https://github.com/wwarthen/RomWBW/pull/90

**Comment by electrified** [comment]
Thanks for merging. It seems to be working OK. Archives generated are ~67MB which I think is greater due to the size of the build tools.

Let me know if you would like it to anything differently.

**Comment by wwarthen** [comment]
It is working great.  Might be possible to clean the intermediate files to reduce the size.  There is probably a way to expose the builds in a way that is easier for casual users to find as well.

Don't change anything right now.  I want to learn a bit more first.

Thanks!

Wayne

**Comment by cm68** [comment]
the directory naming logic goes something like this:

Tools/unix contains the portable shell script(s) and source code of the binary tools
Tools/Linux gets the executables for the linux build
Tools/Darwin gets the executables for the mac os build
the Tools/Makefile.inc points BINDIR at the right executable directory

**Comment by wwarthen** [comment]
I'm going to go ahead and close this issue.  The GitHub CI build process seems to be working fairly well.  We can open new issues if something else is found.

Thanks!
