### ISSUE TITLE
SD and IDE slices probblem

### ISSUE THREAD

**Issue by nbrok** [wwarthen/RomWBW#98]
Hi Wayne,

As I boot directly to an IDE or SD device I see an empty directory. Booting from ROM (typing Z for zsdos) and I see the expected directory. What's wrong?
I did reserve slices with fdisk80 and made a fat partition.

Greetings,

Nick

**Comment by wwarthen** [comment]
Hi Nick,

How did you create your media?  Did you put one of the pre-built disk images on it?  Which slice did you boot from?

When you boot from a disk unit/slice, that selected unit/slice is automatically mapped to A:.  So, you should see whatever files were on that unit/slice.  If there were no files there, then you would see an empty directory.  Pay attention to the list of disk units/slices displayed.

Thanks,

Wayne

**Comment by nbrok** [comment]
I use the syscopied image of the rom on C: (slice 0 I think). Booting with the z command and I get on C: the directory as expected.
Booting from slice 0 directly, it boots but everything is empty.
This is what I see after booting from slice 0:

`CBIOS v2.9.2-pre.33 [WBW]                                                       
                                                                                
Configuring Drives...                                                           
                                                                                
   A:=MD1:0                                                                     
   B:=MD0:0                                                                     
   C:=IDE0:0                                                                    
   D:=IDE0:1                                                                    
   E:=IDE0:2                                                                    
   F:=IDE0:3                                                                    
   G:=SD0:0                                                                     
   H:=SD0:1                                                                     
   I:=SD0:2                                                                     
   J:=SD0:3                                                                     
                                                                                
   1932 Disk Buffer Bytes Free 

ZSDOS V1.1, 54,0K TPA
C:`

Greetings,

Nick

**Comment by wwarthen** [comment]
Hi Nick,

Doesn't make any sense.  Can you send me the entire log of both sessions?  The one where you boot with 'Z' and the one where you boot from a specific unit/slice?

Thanks,

Wayne

**Comment by nbrok** [comment]
Booting from slice 0:
`ROM: (M)onitor (C)P/M (Z)-System (F)orth (B)ASIC (T)-BASIC (P)LAY (U)SER ROM    
Disk: (0)MD1 (1)MD0 (2)IDE0 (3)IDE1 (4)SD0                                      
                                                                                
Boot Selection? 2    Slice(0-9)[0]? 0                                           
                                                                                
Booting Disk Unit 2, Slice 0...                                                 
                                                                                
Reading disk information...                                                     
Loc=D000 End=FE00 Ent=E600 Label=Unlabeled Drive                                
                                                                                
Loading...                                                                      
                                                                                
CBIOS v2.9.2-pre.1 [WBW]                                                        
                                                                                
Configuring Drives...                                                           
                                                                                
   A:=MD1:0                                                                     
   B:=MD0:0                                                                     
   C:=IDE0:0                                                                    
   D:=IDE0:1                                                                    
   E:=IDE1:0                                                                    
   F:=IDE1:1                                                                    
   G:=SD0:0                                                                     
   H:=SD0:1                                                                     
                                                                                
   2487 Disk Buffer Bytes Free                                                  
                                                                                
ZSDOS v1.1, 54.0K TPA                                                           
                                                                                
C>
`
Booting via Z

`Boot Selection? Z                                                               
                                                                                
Loading ZSDOS v1.1...                                                           
                                                                                
                                                                                
                                                                                
CBIOS v2.9.2-pre.33 [WBW]                                                       
                                                                                
Configuring Drives...                                                           
                                                                                
   A:=MD1:0                                                                     
   B:=MD0:0                                                                     
   C:=IDE0:0                                                                    
   D:=IDE0:1                                                                    
   E:=IDE0:2                                                                    
   F:=IDE0:3                                                                    
   G:=SD0:0                                                                     
   H:=SD0:1                                                                     
   I:=SD0:2                                                                     
   J:=SD0:3                                                                     
                                                                                
   1932 Disk Buffer Bytes Free                                                  
                                                                                
ZSDOS v1.1, 54.0K TPA                                                           
                                                                                
B>
`
Greetings,

Nick

**Comment by wwarthen** [comment]
Hi Nick,

OK, this helps.  It appears that Unit 2, Slice 0 contains CBIOS v2.9.2-pre.1.  This CBIOS version is older than the one in your ROM which looks like it is v2.9.2-pre.33.  You will need to use SYSCOPY to update the system tracks on Unit 2, Slice 0.

If you boot from ROM using 'Z', confirm that IDE0:0 is mapped to C:, then use the following command:

B>SYSCOPY C:=ZSYS.SYS

After this, reboot and try booting from Unit 2, Slice 0.

Thanks,

Wayne

**Comment by nbrok** [comment]
Thanks Wayne, this helps. A: is now mapped to my ide disk as expected.

Greetings,

Nick

**Comment by wwarthen** [comment]
Excellent.

I am going to go ahead and close this issue.

Thanks,

Wayne
